{
  "hash": "3095efbb86381c46a93a9353baca0359",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Examinig claims of Racial Bias in Predictive Policing through a Geographic Perspective\nauthors:\n  - name: Fareeza Ali and Jackson Howes\n    affiliation: Georgetown University\n    corresponding: true\nbibliography: references.bib\n---\n---\ntitle: Examinig claims of Racial Bias in Predictive Policing through a Geographic Perspective\nauthors:\n  - name: Fareeza Ali and Jackson Howes\n    affiliation: Georgetown University\n    corresponding: true\nbibliography: references.bib\n---\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.1     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.2.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ purrr::%||%()   masks base::%||%()\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLinking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(tidycensus)\nlibrary(tigris)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTo enable caching of data, set `options(tigris_use_cache = TRUE)`\nin your R script or .Rprofile.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(spdep)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: spData\nTo access larger datasets in this package, install the spDataLarge\npackage with: `install.packages('spDataLarge',\nrepos='https://nowosad.github.io/drat/', type='source')`\n```\n\n\n:::\n:::\n\n\n# Abstract\n\nPredictive policing systems have been repeatedly criticized for reproducing and amplifying racial disparities, yet empirical evaluation is complicated by the fact that “crime data” are not neutral measurements of underlying criminal behavior but administrative records produced through enforcement, reporting, and institutional decision-making. In this manuscript, we assess whether spatial patterns in recorded violent felony incidents changed in ways consistent with the claim that algorithmic policing intensified racially disparate enforcement. We adopt a geographic perspective, using NYPD precincts as the unit of analysis, violent felony complaint records as the outcome, and census-derived racial composition as the principal demographic covariate. Our design compares a pre-period (2010–2012) and a post-period (2017–2019) bracketing the implementation window of Patternizr, a predictive policing system introduced by the NYPD in 2013. We quantify global spatial autocorrelation in both crime rates and Black population share using Moran’s \\(I\\), identify local clusters using Local Indicators of Spatial Association (LISA), and assess whether observed clustering exceeds what would be expected under a population-proportional null model via Monte Carlo simulation. Finally, we use geographically weighted regression (GWR) to examine whether the relationship between racial composition and recorded crime rates became more spatially heterogeneous over time. We emphasize throughout that any observed differences are associational rather than causal, given concurrent neighborhood change and other confounds; nonetheless, this framework isolates concrete, testable spatial signatures that are directly relevant to claims of algorithmically mediated bias.\n\n# Introduction\n\nPublic and scholarly debates over predictive policing have increasingly centered on a shared concern: that algorithmic systems trained on historically patterned enforcement data may re-entrench and intensify the very disparities they purport to mitigate. In the specific context of New York City, Patternizr has been described as a tool intended to assist in recognizing potentially related crime patterns; however, even systems framed as investigative aids may shape enforcement attention and thereby the geography of recorded crime. When police deploy resources unevenly across space, administrative “crime” data can reflect both underlying incidents and the spatial distribution of policing itself. As a result, testing claims of algorithmic bias requires methodological approaches that can separate (or at minimum, describe) changes in spatial concentration and demographic overlap.\n\nWe therefore pose a geographically grounded question: did the spatial structure of recorded violent felony crime become more clustered after the implementation of Patternizr, and did the geography of those clusters align differently with the geography of Black residential concentration? Importantly, our inferential target is not a direct causal estimate of Patternizr’s effect. Instead, we evaluate whether the *spatial signatures* of recorded crime—global clustering, local hot spots, and hot-spot overlap with racially concentrated precincts—changed in ways that are consistent with common critiques of predictive policing. We explicitly treat demographic change, including gentrification and population redistribution between 2010 and 2020, as a major confound that must be described alongside any policing-related interpretation.\n\n# Research Questions and Hypotheses\n\nOur analysis is organized around three primary research questions.\n\n1. **Did the spatial clustering of violent felony *crime rates* change between the pre-Patternizr and post-Patternizr periods?**  \n   If predictive policing concentrated enforcement attention into a narrower set of precincts, we would expect increased spatial autocorrelation in recorded crime rates. This motivates comparison of global Moran’s \\(I\\) for precinct-level crime rates across periods.\n\n2. **Did the spatial clustering of Black residential concentration change over the same window, and how does it relate to crime clustering?**  \n   Racial residential segregation produces strong spatial autocorrelation in demographic composition. If this structure is stable while crime clustering changes, then changes in the *relationship* between demographic clustering and crime clustering become substantively interpretable.\n\n3. **Did the overlap between crime hot spots and Black population hot spots change?**  \n   We operationalize “hot spot” using LISA High–High clusters. A reduction in overlap may indicate either (i) a weakening association between racial concentration and recorded crime hot spots, or (ii) demographic change in the precincts that previously occupied both categories.\n\nIn addition, we use geographically weighted regression (GWR) as a diagnostic to evaluate whether the local association between percent Black and precinct crime rates became more spatially heterogeneous over time. Substantively, a shift toward stronger spatial non-stationarity is consistent with a more localized policing geography, but this pattern can also arise from localized neighborhood change and other place-specific dynamics.\n\n# Data and Study Design\n\n## Spatial Units and Coordinate Systems\n\nThe unit of analysis is the NYPD precinct. We load an official precinct boundary shapefile and project it to an equal-area / planar coordinate system appropriate for spatial operations (EPSG:32118). All spatial overlays and neighborhood constructions (contiguity weights) are conducted in this projected CRS to ensure that area calculations and adjacency relationships are well-defined.\n\nLOAD PRECINT SHAPEFILE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprecincts <- st_read(\"data/data/nyc_precincts.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `nyc_precincts' from data source \n  `/home/jmchowes/Georgetown DSAN/Semester 1/DSAN 6750/Project/GIS_Final/data/data/nyc_precincts.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 77 features and 3 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -74.25559 ymin: 40.49613 xmax: -73.70001 ymax: 40.91553\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_proj <- st_transform(precincts, 32118)\n```\n:::\n\n\n## Demographic Data: Census Blocks to Precincts via Areal Interpolation\n\nBecause precinct boundaries do not align with census block boundaries, we construct precinct-level demographics using areal interpolation. Specifically, we obtain census block geometries and block-level decennial census counts for 2010 and 2020. For each census year, we intersect census blocks with precinct polygons, compute the proportion of each block’s area contained within each precinct, and allocate block-level counts proportionally to those intersection weights. Summing the allocated counts across intersections yields precinct-level demographic totals.\n\nDOWNLOAD 2020 BLOCK GEOMs\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nblocks_2020 <- st_read(\"data/data/tl_2020_36_tabblock20/tl_2020_36_tabblock20.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `tl_2020_36_tabblock20' from data source \n  `/home/jmchowes/Georgetown DSAN/Semester 1/DSAN 6750/Project/GIS_Final/data/data/tl_2020_36_tabblock20/tl_2020_36_tabblock20.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 288819 features and 17 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -79.76259 ymin: 40.47658 xmax: -71.77749 ymax: 45.01586\nGeodetic CRS:  NAD83\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnyc_counties <- c(\"005\", \"047\", \"061\", \"081\", \"085\")\nblocks_2020_nyc <- blocks_2020 %>%\n  filter(COUNTYFP20 %in% nyc_counties)\n\n# Pull 2020 census data\np1_2020 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P1_001N\", \"P1_003N\", \"P1_004N\", \"P1_005N\", \n                \"P1_006N\", \"P1_007N\", \"P1_008N\", \"P1_009N\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2020,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2020 decennial Census\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: • You have not set a Census API key. Users without a key are limited to 500\nqueries per day and may experience performance limitations.\nℹ For best results, get a Census API key at\nhttp://api.census.gov/data/key_signup.html and then supply the key to the\n`census_api_key()` function to use it throughout your tidycensus session.\nThis warning is displayed once per session.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing the PL 94-171 Redistricting Data Summary File\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNote: 2020 decennial Census data use differential privacy, a technique that\nintroduces errors into data to preserve respondent confidentiality.\nℹ Small counts should be interpreted with caution.\nℹ See https://www.census.gov/library/fact-sheets/2021/protecting-the-confidentiality-of-the-2020-census-redistricting-data.html for additional guidance.\nThis message is displayed once per session.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\np2_2020 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P2_001N\", \"P2_002N\", \"P2_003N\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2020,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2020 decennial Census\nUsing the PL 94-171 Redistricting Data Summary File\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Join and interpolate 2020 data to precincts\np1_2020 <- p1_2020 %>% rename(GEOID20 = GEOID)\np2_2020 <- p2_2020 %>% rename(GEOID20 = GEOID)\n\nblocks_demo_2020 <- blocks_2020_nyc %>%\n  left_join(p1_2020, by = \"GEOID20\") %>%\n  left_join(p2_2020, by = \"GEOID20\")\n\nblocks_2020_proj <- st_transform(blocks_demo_2020, 32118)\n\nblocks_2020_proj <- blocks_2020_proj %>%\n  mutate(block_area = st_area(geometry))\n\nblock_precinct_int_2020 <- st_intersection(blocks_2020_proj, precincts_proj)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: attribute variables are assumed to be spatially constant throughout\nall geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nblock_precinct_int_2020 <- block_precinct_int_2020 %>%\n  mutate(\n    piece_area = st_area(geometry),\n    weight = as.numeric(piece_area / block_area)\n  )\n\ndemo_vars_2020 <- c(\"P1_001N\", \"P1_003N\", \"P1_004N\", \"P1_005N\",\n                    \"P1_006N\", \"P1_007N\", \"P1_008N\", \"P1_009N\",\n                    \"P2_001N\", \"P2_002N\", \"P2_003N\")\n\nfor (v in demo_vars_2020) {\n  block_precinct_int_2020[[paste0(v, \"_alloc\")]] <-\n    block_precinct_int_2020[[v]] * block_precinct_int_2020$weight\n}\n\nprecinct_demographics_2020 <- block_precinct_int_2020 %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(across(ends_with(\"_alloc\"), sum, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There was 1 warning in `summarise()`.\nℹ In argument: `across(ends_with(\"_alloc\"), sum, na.rm = TRUE)`.\nℹ In group 1: `precinct = \"1\"`.\nCaused by warning:\n! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.\nSupply arguments directly to `.fns` through an anonymous function instead.\n\n  # Previously\n  across(a:b, mean, na.rm = TRUE)\n\n  # Now\n  across(a:b, \\(x) mean(x, na.rm = TRUE))\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_2020 <- precincts_proj %>%\n  left_join(precinct_demographics_2020, by = \"precinct\")\n```\n:::\n\n\nDOWNLOAD 2010 BLOCK GEOMs\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nblocks_2010 <- blocks(state = \"NY\", county = nyc_counties, year = 2010)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  84%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |======================================================================| 100%\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |======================================================================| 100%\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |======================================================================| 100%\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |==========================================                            |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |=============================================================         |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  91%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nblocks_2010_nyc <- blocks_2010 %>%\n  filter(COUNTYFP10 %in% nyc_counties)\n\n# Pull 2010 census data\np1_2010 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P003001\", \"P003002\", \"P003003\", \"P003004\",\n                \"P003005\", \"P003006\", \"P003007\", \"P003008\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2010,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2010 decennial Census\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing Census Summary File 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\np2_2010 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P004001\", \"P004002\", \"P004003\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2010,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2010 decennial Census\nUsing Census Summary File 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Join and interpolate 2010 data to precincts\np1_2010 <- p1_2010 %>% rename(GEOID10 = GEOID)\np2_2010 <- p2_2010 %>% rename(GEOID10 = GEOID)\n\nblocks_demo_2010 <- blocks_2010_nyc %>%\n  left_join(p1_2010, by = \"GEOID10\") %>%\n  left_join(p2_2010, by = \"GEOID10\")\n\nblocks_2010_proj <- st_transform(blocks_demo_2010, 32118)\n\nblocks_2010_proj <- blocks_2010_proj %>%\n  mutate(block_area = st_area(geometry))\n\nblock_precinct_int_2010 <- st_intersection(blocks_2010_proj, precincts_proj)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: attribute variables are assumed to be spatially constant throughout\nall geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nblock_precinct_int_2010 <- block_precinct_int_2010 %>%\n  mutate(\n    piece_area = st_area(geometry),\n    weight = as.numeric(piece_area / block_area)\n  )\n\ndemo_vars_2010 <- c(\"P003001\", \"P003002\", \"P003003\", \"P003004\",\n                    \"P003005\", \"P003006\", \"P003007\", \"P003008\",\n                    \"P004001\", \"P004002\", \"P004003\")\n\nfor (v in demo_vars_2010) {\n  block_precinct_int_2010[[paste0(v, \"_alloc\")]] <-\n    block_precinct_int_2010[[v]] * block_precinct_int_2010$weight\n}\n\nprecinct_demographics_2010 <- block_precinct_int_2010 %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(across(ends_with(\"_alloc\"), sum, na.rm = TRUE))\n\nprecincts_2010 <- precincts_proj %>%\n  left_join(precinct_demographics_2010, by = \"precinct\")\n```\n:::\n\n\nFormally, let \\(b\\) index census blocks and \\(p\\) index precincts. Define the intersection area \\(A_{bp} = \\text{area}(b \\cap p)\\) and block area \\(A_b = \\text{area}(b)\\). The areal weight is\n\n$$\nw_{bp} = \\frac{A_{bp}}{A_b}.\n$$\n\nFor a block-level count \\(X_b\\) (e.g., total population, race counts), the precinct-allocated contribution from block \\(b\\) is\n\n$$\nX_{bp}^{\\text{alloc}} = w_{bp} X_b,\n$$\n\nand the precinct-level total is\n\n$$\nX_p = \\sum_{b} X_{bp}^{\\text{alloc}}.\n$$\n\nWe then compute precinct demographic shares (e.g., percent Black) as\n\n$$\n\\%Black_p = 100 \\times \\frac{Black_p}{TotalPop_p},\n$$\n\nwith analogous definitions for percent Hispanic and percent White.\n\nThis approach implicitly assumes uniform population density within each block. While imperfect, it is standard practice when translating census counts to non-nested administrative boundaries, and it produces internally consistent precinct-level denominators for per-capita crime rate computation.\n\n## Crime Data: Violent Felony Complaint Records\n\nWe load a cleaned violent felony complaint dataset containing point locations (latitude/longitude) and complaint dates. Complaint points are converted into an `sf` point object in WGS84 (EPSG:4326) and then filtered to a bounding box corresponding to New York City to remove obvious geocoding errors. Points are subsequently projected into EPSG:32118 for spatial joins and distance-consistent operations. Complaint dates are parsed to extract year, enabling period-based subsetting.\n\nSTANDARDIZE COL NAMES\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprecincts_2010 <- precincts_2010 %>%\n  rename(\n    total_pop_alloc = P003001_alloc,\n    white_alloc = P003002_alloc,\n    black_alloc = P003003_alloc,\n    aian_alloc = P003004_alloc,\n    asian_alloc = P003005_alloc,\n    nhpi_alloc = P003006_alloc,\n    other_alloc = P003007_alloc,\n    two_or_more_alloc = P003008_alloc,\n    hispanic_total_alloc = P004001_alloc,\n    hispanic_alloc = P004002_alloc,\n    not_hispanic_alloc = P004003_alloc\n  )\n\nprecincts_2020 <- precincts_2020 %>%\n  rename(\n    total_pop_alloc = P1_001N_alloc,\n    white_alloc = P1_003N_alloc,\n    black_alloc = P1_004N_alloc,\n    aian_alloc = P1_005N_alloc,\n    asian_alloc = P1_006N_alloc,\n    nhpi_alloc = P1_007N_alloc,\n    other_alloc = P1_008N_alloc,\n    two_or_more_alloc = P1_009N_alloc,\n    hispanic_total_alloc = P2_001N_alloc,\n    hispanic_alloc = P2_002N_alloc,\n    not_hispanic_alloc = P2_003N_alloc\n  )\n```\n:::\n\n\nLOAD AND PREP CRIME DATA\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nviolent_crimes <- read.csv(\"data/data/violent_felony_cleaned_13.csv\")\n\nviolent_sf <- st_as_sf(\n  violent_crimes,\n  coords = c(\"long\", \"lat\"),\n  crs = 4326\n)\n\nviolent_sf <- violent_sf %>%\n  filter(\n    !is.na(geometry),\n    sf::st_coordinates(geometry)[, 1] > -74.5,\n    sf::st_coordinates(geometry)[, 1] < -73.7,\n    sf::st_coordinates(geometry)[, 2] > 40.45,\n    sf::st_coordinates(geometry)[, 2] < 40.95\n  )\n\nviolent_proj <- st_transform(violent_sf, 32118)\n\nviolent_proj <- violent_proj %>%\n  mutate(\n    complaint_date = as.Date(complaint_date),\n    year = as.integer(format(complaint_date, \"%Y\"))\n  )\n```\n:::\n\n\n## Pre/Post Comparison Windows\n\nTo reduce transitional ambiguity surrounding the implementation timeline, we define two non-overlapping windows:\n\n- **Before**: 2010–2012  \n- **After**: 2017–2019  \n\nFor each period, we spatially join complaint points to precinct polygons, count incidents per precinct, and compute the precinct-level violent felony rate per 1,000 residents:\n\n$$\nCrimeRate_p = 1000 \\times \\frac{Crimes_p}{TotalPop_p}.\n$$\n\nWe exclude precinct 22 (Central Park) due to its negligible residential population, which otherwise induces artificially inflated per-capita rates and undermines interpretability.\n\nBEFORE/AFTER DATASETS\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Filter crimes by period\ncrimes_before <- violent_proj %>% filter(year >= 2010 & year <= 2012)\ncrimes_after <- violent_proj %>% filter(year >= 2017 & year <= 2019)\n\nprint(paste(\"Crimes before (2010-2012):\", nrow(crimes_before)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Crimes before (2010-2012): 201231\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"Crimes after (2017-2019):\", nrow(crimes_after)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Crimes after (2017-2019): 162599\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Count crimes per precinct - BEFORE\ncrime_counts_before <- crimes_before %>%\n  st_join(precincts_proj, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(total_crimes = n(), .groups = \"drop\")\n\nprecincts_before <- precincts_2010 %>%\n  left_join(crime_counts_before, by = \"precinct\") %>%\n  mutate(\n    total_crimes = replace_na(total_crimes, 0),\n    crime_rate = (total_crimes / total_pop_alloc) * 1000,\n    pct_black = (black_alloc / total_pop_alloc) * 100,\n    pct_hispanic = (hispanic_alloc / total_pop_alloc) * 100,\n    pct_white = (white_alloc / total_pop_alloc) * 100\n  )\n\n# Count crimes per precinct - AFTER\ncrime_counts_after <- crimes_after %>%\n  st_join(precincts_proj, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(total_crimes = n(), .groups = \"drop\")\n\nprecincts_after <- precincts_2020 %>%\n  left_join(crime_counts_after, by = \"precinct\") %>%\n  mutate(\n    total_crimes = replace_na(total_crimes, 0),\n    crime_rate = (total_crimes / total_pop_alloc) * 1000,\n    pct_black = (black_alloc / total_pop_alloc) * 100,\n    pct_hispanic = (hispanic_alloc / total_pop_alloc) * 100,\n    pct_white = (white_alloc / total_pop_alloc) * 100\n  )\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Remove Central Park (Precinct 22) - negligible residential population\nprecincts_before <- precincts_before %>% filter(precinct != \"22\")\nprecincts_after <- precincts_after %>% filter(precinct != \"22\")\n\nprint(paste(\"Precincts remaining (before):\", nrow(precincts_before)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Precincts remaining (before): 76\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"Precincts remaining (after):\", nrow(precincts_after)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Precincts remaining (after): 76\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Verify new summary stats\nprint(\"=== BEFORE (excluding Central Park) ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== BEFORE (excluding Central Park) ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_before$crime_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  6.386  18.089  24.631  27.589  34.098 115.440 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"=== AFTER (excluding Central Park) ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== AFTER (excluding Central Park) ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_after$crime_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  4.083  11.486  18.550  20.758  25.681  78.110 \n```\n\n\n:::\n:::\n\n\n# Methods Overview\n\nOur empirical strategy combines (i) global measures of spatial autocorrelation, (ii) local cluster detection, (iii) a simulation-based null model to benchmark observed clustering, and (iv) a spatially varying regression diagnostic. These components correspond directly to the computational workflow implemented below.\n\n## Global Spatial Autocorrelation: Moran’s \\(I\\)\n\nWe quantify global spatial autocorrelation using Moran’s \\(I\\) for two variables: (a) precinct crime rates and (b) percent Black population. Spatial dependence is defined using a queen contiguity neighborhood structure (shared edges or corners). Let \\(x_p\\) denote a precinct-level variable (e.g., crime rate) and \\(\\bar{x}\\) its mean. With spatial weights \\(w_{pq}\\) (row-standardized), Moran’s \\(I\\) is\n\n$$\nI = \\frac{n}{S_0}\\frac{\\sum_{p}\\sum_{q} w_{pq}(x_p - \\bar{x})(x_q - \\bar{x})}{\\sum_{p}(x_p - \\bar{x})^2},\n$$\n\nwhere \\(n\\) is the number of precincts and \\(S_0 = \\sum_{p}\\sum_{q} w_{pq}\\). We compute Moran’s \\(I\\) separately for each period and interpret differences as changes in the degree of clustering in the precinct-level surfaces.\n\nVERIFY DATA & check for outliers\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Summary stats\nprint(\"=== BEFORE PERIOD (2010-2012 crimes + 2010 census) ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== BEFORE PERIOD (2010-2012 crimes + 2010 census) ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"N precincts:\", nrow(precincts_before)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"N precincts: 76\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_before$crime_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  6.386  18.089  24.631  27.589  34.098 115.440 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_before$pct_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.041   5.261  16.000  26.677  41.335  91.542 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"=== AFTER PERIOD (2017-2019 crimes + 2020 census) ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== AFTER PERIOD (2017-2019 crimes + 2020 census) ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"N precincts:\", nrow(precincts_after)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"N precincts: 76\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_after$crime_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  4.083  11.486  18.550  20.758  25.681  78.110 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_after$pct_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.091   5.030  13.922  22.969  33.941  81.462 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Top crime rate precincts (sanity check)\nprint(\"=== Top 5 crime rates - BEFORE ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== Top 5 crime rates - BEFORE ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_before %>%\n  st_drop_geometry() %>%\n  select(precinct, total_crimes, total_pop_alloc, crime_rate) %>%\n  arrange(desc(crime_rate)) %>%\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct total_crimes total_pop_alloc crime_rate\n1       14         2378        20599.48  115.43978\n2       41         3339        52157.85   64.01721\n3       73         5411        86541.43   62.52496\n4       81         3621        62776.77   57.68057\n5       25         2440        47368.53   51.51099\n```\n\n\n:::\n:::\n\n\nSPATIAL WEIGHTS AND MORANS I\nCREATE SPATIAL WEIGHTS MATRIX\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# We need to create weights for BOTH datasets\n# Since we removed precinct 22, we need fresh neighbor structures\n\n# Convert to sp objects for spdep\nprecincts_before_sp <- as(precincts_before, \"Spatial\")\nprecincts_after_sp <- as(precincts_after, \"Spatial\")\n\n# Create queen contiguity neighbors (precincts sharing edges or corners)\nnb_before <- poly2nb(precincts_before_sp, queen = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in poly2nb(precincts_before_sp, queen = TRUE): neighbour object has 3 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnb_after <- poly2nb(precincts_after_sp, queen = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in poly2nb(precincts_after_sp, queen = TRUE): neighbour object has 3 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Convert to spatial weights (row-standardized)\nweights_before <- nb2listw(nb_before, style = \"W\", zero.policy = TRUE)\nweights_after <- nb2listw(nb_after, style = \"W\", zero.policy = TRUE)\n\nprint(\"Spatial weights created successfully\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Spatial weights created successfully\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"Average # of neighbors (before):\", round(mean(card(nb_before)), 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Average # of neighbors (before): 4.18\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"Average # of neighbors (after):\", round(mean(card(nb_after)), 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Average # of neighbors (after): 4.18\"\n```\n\n\n:::\n:::\n\n\nGLOBAL MORANS I FOR CRIME RATE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprint(\"========== GLOBAL MORAN'S I: CRIME RATE ==========\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"========== GLOBAL MORAN'S I: CRIME RATE ==========\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Before period\nmoran_crime_before <- moran.test(precincts_before$crime_rate, weights_before)\nprint(\"--- BEFORE (2010-2012) ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- BEFORE (2010-2012) ---\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(moran_crime_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_before$crime_rate  \nweights: weights_before    \n\nMoran I statistic standard deviate = 3.7442, p-value = 9.047e-05\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.269439611      -0.013333333       0.005703561 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# After period\nmoran_crime_after <- moran.test(precincts_after$crime_rate, weights_after)\nprint(\"--- AFTER (2017-2019) ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- AFTER (2017-2019) ---\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(moran_crime_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_after$crime_rate  \nweights: weights_after    \n\nMoran I statistic standard deviate = 4.5223, p-value = 3.059e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.341083493      -0.013333333       0.006142037 \n```\n\n\n:::\n:::\n\n\nGOBAL MORANS I FOR PERCENT OF BLACK POP\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprint(\"========== GLOBAL MORAN'S I: PCT BLACK ==========\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"========== GLOBAL MORAN'S I: PCT BLACK ==========\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Before period\nmoran_black_before <- moran.test(precincts_before$pct_black, weights_before)\nprint(\"--- BEFORE (2010-2012) ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- BEFORE (2010-2012) ---\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(moran_black_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_before$pct_black  \nweights: weights_before    \n\nMoran I statistic standard deviate = 7.1848, p-value = 3.366e-13\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.570490119      -0.013333333       0.006602919 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# After period\nmoran_black_after <- moran.test(precincts_after$pct_black, weights_after)\nprint(\"--- AFTER (2017-2019) ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"--- AFTER (2017-2019) ---\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(moran_black_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_after$pct_black  \nweights: weights_after    \n\nMoran I statistic standard deviate = 7.0478, p-value = 9.092e-13\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.557878445      -0.013333333       0.006568909 \n```\n\n\n:::\n:::\n\n\nSUMMARY TABLE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmoran_summary <- data.frame(\n  Variable = c(\"Crime Rate\", \"Crime Rate\", \"Pct Black\", \"Pct Black\"),\n  Period = c(\"Before\", \"After\", \"Before\", \"After\"),\n  Morans_I = c(\n    moran_crime_before$estimate[\"Moran I statistic\"],\n    moran_crime_after$estimate[\"Moran I statistic\"],\n    moran_black_before$estimate[\"Moran I statistic\"],\n    moran_black_after$estimate[\"Moran I statistic\"]\n  ),\n  P_Value = c(\n    moran_crime_before$p.value,\n    moran_crime_after$p.value,\n    moran_black_before$p.value,\n    moran_black_after$p.value\n  )\n)\n\nprint(\"========== MORAN'S I SUMMARY ==========\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"========== MORAN'S I SUMMARY ==========\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(moran_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Variable Period  Morans_I      P_Value\n1 Crime Rate Before 0.2694396 9.046675e-05\n2 Crime Rate  After 0.3410835 3.058752e-06\n3  Pct Black Before 0.5704901 3.365746e-13\n4  Pct Black  After 0.5578784 9.091641e-13\n```\n\n\n:::\n:::\n\n\nCrime Rate\nPeriodMoran's Ip-valueInterpretationBefore0.2690.00009Moderate positive clustering, highly significantAfter0.3410.000003Stronger positive clustering, highly significant\nWhat this means:\n\nCrime is spatially clustered in both periods (not randomly distributed)\nHigh-crime precincts tend to be near other high-crime precincts\nThe clustering INCREASED after Patternizr (0.269 → 0.341)\n\nPercent Black\nPeriodMoran's Ip-valueInterpretationBefore0.570~0Strong positive clusteringAfter0.558~0Strong positive clustering\nWhat this means:\n\nRacial composition is highly clustered (this is segregation - no surprise)\nPrecincts with high Black populations are near other precincts with high Black populations\nThis didn't change much between periods (0.570 → 0.558)\n\n\nThe Interesting Finding\nCrime rate clustering increased after Patternizr (0.269 → 0.341), while racial clustering stayed basically the same.\nThis could suggest:\n\nPatternizr concentrated policing in certain areas (creating more spatial clustering of recorded crime)\nOr crime patterns genuinely became more geographically concentrated\nOr other factors changed between 2010-2012 and 2017-2019\n\n\n## Local Moran’s \\(I\\) and LISA Cluster Typology\n\nTo identify localized clusters and spatial outliers, we compute Local Moran’s \\(I\\) (LISA) for both crime rates and percent Black. We classify each precinct into one of five categories based on the sign of its standardized value and the sign of its spatial lag (neighbors’ average), conditional on statistical significance:\n\n- High–High (hot spot): high value surrounded by high values  \n- Low–Low (cold spot): low value surrounded by low values  \n- High–Low: high outlier surrounded by low values  \n- Low–High: low outlier surrounded by high values  \n- Not significant\n\nThe key substantive comparison is whether High–High crime precincts co-occur with High–High Black precincts, and whether the count (and identity) of overlapping precincts changes from the pre-period to the post-period.\n\nLOCAL MORANS I (LISA)\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# BEFORE period\nlisa_crime_before <- localmoran(precincts_before$crime_rate, weights_before)\nlisa_black_before <- localmoran(precincts_before$pct_black, weights_before)\n\n# AFTER period\nlisa_crime_after <- localmoran(precincts_after$crime_rate, weights_after)\nlisa_black_after <- localmoran(precincts_after$pct_black, weights_after)\n```\n:::\n\n\nCREATE LISA CLUSTER CATS\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nget_lisa_clusters <- function(variable, lisa_output, weights) {\n  # Get standardized values\n  z <- scale(variable)[,1]\n  \n  # Get lagged values (neighbors' average)\n  lag_z <- lag.listw(weights, z)\n  \n  # Get p-values (using column 5: Pr(z != E(Ii)))\n  p_value <- lisa_output[, 5]\n  \n  # Classify into quadrants\n  cluster <- case_when(\n    p_value > 0.05 ~ \"Not Significant\",\n    z > 0 & lag_z > 0 ~ \"High-High\",\n    z < 0 & lag_z < 0 ~ \"Low-Low\",\n    z > 0 & lag_z < 0 ~ \"High-Low\",\n    z < 0 & lag_z > 0 ~ \"Low-High\",\n    TRUE ~ \"Not Significant\"\n  )\n  \n  return(cluster)\n}\n\n# Apply to all four combinations\nprecincts_before$lisa_crime <- get_lisa_clusters(\n  precincts_before$crime_rate, lisa_crime_before, weights_before\n)\nprecincts_before$lisa_black <- get_lisa_clusters(\n  precincts_before$pct_black, lisa_black_before, weights_before\n)\n\nprecincts_after$lisa_crime <- get_lisa_clusters(\n  precincts_after$crime_rate, lisa_crime_after, weights_after\n)\nprecincts_after$lisa_black <- get_lisa_clusters(\n  precincts_after$pct_black, lisa_black_after, weights_after\n)\n```\n:::\n\n\nSUMMARY TABLE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprint(\"=== LISA Clusters: CRIME RATE ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== LISA Clusters: CRIME RATE ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"BEFORE:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BEFORE:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(table(precincts_before$lisa_crime))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not Significant \n              6               1               1              68 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"AFTER:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AFTER:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(table(precincts_after$lisa_crime))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not Significant \n              4               1               1              70 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"=== LISA Clusters: PCT BLACK ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== LISA Clusters: PCT BLACK ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"BEFORE:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BEFORE:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(table(precincts_before$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not Significant \n              7               2               2              65 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"AFTER:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AFTER:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(table(precincts_after$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High         Low-Low Not Significant \n              6               1              69 \n```\n\n\n:::\n:::\n\n\nKEY QUESTION - OVERLAP???\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprint(\"=== OVERLAP: High-High Crime AND High-High Black ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== OVERLAP: High-High Crime AND High-High Black ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Before period\noverlap_before <- precincts_before %>%\n  st_drop_geometry() %>%\n  filter(lisa_crime == \"High-High\" & lisa_black == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black)\n\nprint(\"BEFORE - Precincts that are High-High for BOTH crime and Black population:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BEFORE - Precincts that are High-High for BOTH crime and Black population:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(overlap_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct crime_rate pct_black\n1       73   62.52496  81.73487\n2       77   39.89329  72.30491\n3       81   57.68057  80.20771\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"Count:\", nrow(overlap_before)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Count: 3\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# After period\noverlap_after <- precincts_after %>%\n  st_drop_geometry() %>%\n  filter(lisa_crime == \"High-High\" & lisa_black == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black)\n\nprint(\"AFTER - Precincts that are High-High for BOTH crime and Black population:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AFTER - Precincts that are High-High for BOTH crime and Black population:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(overlap_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] precinct   crime_rate pct_black \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(paste(\"Count:\", nrow(overlap_after)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Count: 0\"\n```\n\n\n:::\n:::\n\n\nCROSS TABULATION\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprint(\"=== Full Cross-Tabulation: Crime Clusters vs Black Clusters ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== Full Cross-Tabulation: Crime Clusters vs Black Clusters ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"BEFORE:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BEFORE:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(table(precincts_before$lisa_crime, precincts_before$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 \n                  High-High Low-High Low-Low Not Significant\n  High-High               3        1       0               2\n  Low-High                0        0       0               1\n  Low-Low                 0        0       1               0\n  Not Significant         4        1       1              62\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"AFTER:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AFTER:\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(table(precincts_after$lisa_crime, precincts_after$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 \n                  High-High Low-Low Not Significant\n  High-High               0       0               4\n  Low-High                0       0               1\n  Low-Low                 0       1               0\n  Not Significant         6       0              64\n```\n\n\n:::\n:::\n\n\nKey Results\nBefore Patternizr (2010-2012)\n\n3 precincts were High-High for BOTH crime and Black population\nThese were precincts 73, 77, and 81 (all in Brooklyn, likely Brownsville/East New York area)\nCrime rates: 40-63 per 1,000\nBlack population: 72-82%\n\nAfter Patternizr (2017-2019)\n\n0 precincts were High-High for BOTH crime and Black population\nThe overlap completely disappeared!\n\nWhat Does This Mean?\nThis is actually a nuanced finding. Let's look at what changed:\nMetricBeforeAfterChangeHigh-High Crime precincts64↓ Fewer crime hot spotsHigh-High Black precincts76↓ Slightly fewerOverlap (both High-High)30↓ No overlap\nPossible Interpretations\n\nOptimistic interpretation: Policing became more equitable - crime hot spots are no longer concentrated in predominantly Black neighborhoods\nAlternative interpretation: Crime recording patterns changed - perhaps Patternizr shifted where crimes were being recorded/prioritized\nDemographic shift: Some neighborhoods may have gentrified between 2010 and 2020, changing the racial composition\n\nDIGGING DEEPER\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# What happened to precincts 73, 77, 81?\ntrack_precincts <- c(\"73\", \"77\", \"81\")\n\nprint(\"=== Tracking Precincts 73, 77, 81 ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== Tracking Precincts 73, 77, 81 ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"BEFORE (2010-2012):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BEFORE (2010-2012):\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_before %>%\n  st_drop_geometry() %>%\n  filter(precinct %in% track_precincts) %>%\n  select(precinct, total_crimes, crime_rate, pct_black, lisa_crime, lisa_black) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct total_crimes crime_rate pct_black lisa_crime lisa_black\n1       73         5411   62.52496  81.73487  High-High  High-High\n2       77         3597   39.89329  72.30491  High-High  High-High\n3       81         3621   57.68057  80.20771  High-High  High-High\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(\"AFTER (2017-2019):\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AFTER (2017-2019):\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_after %>%\n  st_drop_geometry() %>%\n  filter(precinct %in% track_precincts) %>%\n  select(precinct, total_crimes, crime_rate, pct_black, lisa_crime, lisa_black) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct total_crimes crime_rate pct_black      lisa_crime      lisa_black\n1       73         4254   43.16300  71.84071 Not Significant       High-High\n2       77         2467   24.36427  50.39772 Not Significant       High-High\n3       81         2601   37.73448  58.09961 Not Significant Not Significant\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Also: which precincts ARE High-High for crime in the AFTER period?\nprint(\"=== Which precincts are High-High for crime AFTER? ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== Which precincts are High-High for crime AFTER? ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_after %>%\n  st_drop_geometry() %>%\n  filter(lisa_crime == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black, lisa_black) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct crime_rate pct_black      lisa_black\n1       40   49.56718  34.22379 Not Significant\n2       41   50.61239  30.28773 Not Significant\n3       42   36.31798  45.89912 Not Significant\n4       44   29.94631  33.84694 Not Significant\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# And which are High-High for Black population AFTER?\nprint(\"=== Which precincts are High-High for Black pop AFTER? ===\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"=== Which precincts are High-High for Black pop AFTER? ===\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_after %>%\n  st_drop_geometry() %>%\n  filter(lisa_black == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black, lisa_crime) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct crime_rate pct_black      lisa_crime\n1       67   24.55377  80.40893 Not Significant\n2       63   11.55723  43.82666 Not Significant\n3       69   17.14669  81.46211 Not Significant\n4       73   43.16300  71.84071 Not Significant\n5       77   24.36427  50.39772 Not Significant\n6      100   19.17792  24.78987 Not Significant\n```\n\n\n:::\n:::\n\n\n\"=== Tracking Precincts 73, 77, 81 ===\"\n[1] \"BEFORE (2010-2012):\"\n  precinct total_crimes crime_rate pct_black lisa_crime lisa_black\n1       73         5411   62.52496  81.73487  High-High  High-High\n2       77         3597   39.89329  72.30491  High-High  High-High\n3       81         3621   57.68057  80.20771  High-High  High-High\n[1] \"AFTER (2017-2019):\"\n  precinct total_crimes crime_rate pct_black      lisa_crime      lisa_black\n1       73         4254   43.16300  71.84071 Not Significant       High-High\n2       77         2467   24.36427  50.39772 Not Significant       High-High\n3       81         2601   37.73448  58.09961 Not Significant Not Significant\n[1] \"=== Which precincts are High-High for crime AFTER? ===\"\n  precinct crime_rate pct_black      lisa_black\n1       40   49.56718  34.22379 Not Significant\n2       41   50.61239  30.28773 Not Significant\n3       42   36.31798  45.89912 Not Significant\n4       44   29.94631  33.84694 Not Significant\n[1] \"=== Which precincts are High-High for Black pop AFTER? ===\"\n  precinct crime_rate pct_black      lisa_crime\n1       67   24.55377  80.40893 Not Significant\n2       63   11.55723  43.82666 Not Significant\n3       69   17.14669  81.46211 Not Significant\n4       73   43.16300  71.84071 Not Significant\n5       77   24.36427  50.39772 Not Significant\n6      100   19.17792  24.78987 Not Significant\n\nWhat Happened to Precincts 73, 77, 81\nPrecinctCrime Rate BEFORECrime Rate AFTERChangePct Black BEFOREPct Black AFTERChange7362.543.2↓ 31%81.7%71.8%↓ 10 pts7739.924.4↓ 39%72.3%50.4%↓ 22 pts8157.737.7↓ 35%80.2%58.1%↓ 22 pts\nKey Observations\n\nCrime rates dropped substantially in all three precincts (31-39% decrease)\nBlack population percentages also dropped (likely gentrification in these Brooklyn neighborhoods)\nThese precincts went from \"High-High\" to \"Not Significant\" for crime - meaning they're no longer statistical outliers\n\nInterpretation? POTENTIAL:\n\nGeographic shift: Crime hot spots moved from predominantly Black Brooklyn neighborhoods to more diverse Bronx neighborhoods\nGentrification effect: Precincts 73, 77, 81 experienced significant demographic change (20+ percentage point drops in Black population), which may have come with reduced crime\nPatternizr effect?: Harder to claim directly - the algorithm may have changed policing patterns, but demographic shifts are a major confound\n\nTAKEAWAY: The spatial overlap between crime hot spots and predominantly Black neighborhoods decreased between the pre-Patternizr (2010-2012) and post-Patternizr (2017-2019) periods. However, this change coincided with substantial demographic shifts in the original hot spot precincts, making it difficult to attribute the change solely to the predictive policing algorithm.\n\n\nLISA MAPS\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# ============================================\n# 9G: LISA CLUSTER MAPS\n# ============================================\n\nlibrary(ggplot2)\n\n# Define color scheme for LISA clusters\nlisa_colors <- c(\n  \"High-High\" = \"#E41A1C\",    # Red - hot spots\n  \"Low-Low\" = \"#377EB8\",       # Blue - cold spots\n  \"High-Low\" = \"#FF7F00\",      # Orange - outliers\n  \"Low-High\" = \"#984EA3\",      # Purple - outliers\n  \"Not Significant\" = \"#D3D3D3\" # Gray\n)\n\n# --------------------------------------------\n# CRIME RATE LISA MAPS\n# --------------------------------------------\n\n# Before\nmap_crime_before <- ggplot(precincts_before) +\n  geom_sf(aes(fill = lisa_crime), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"LISA Cluster\") +\n  theme_minimal() +\n  labs(\n    title = \"Crime Rate Clusters: BEFORE Patternizr (2010-2012)\",\n    subtitle = \"Local Moran's I cluster classification\"\n  ) +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nprint(map_crime_before)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# After\nmap_crime_after <- ggplot(precincts_after) +\n  geom_sf(aes(fill = lisa_crime), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"LISA Cluster\") +\n  theme_minimal() +\n  labs(\n    title = \"Crime Rate Clusters: AFTER Patternizr (2017-2019)\",\n    subtitle = \"Local Moran's I cluster classification\"\n  ) +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nprint(map_crime_after)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-2.png)\n:::\n\n```{.r .cell-code .hidden}\n# --------------------------------------------\n# PCT BLACK LISA MAPS\n# --------------------------------------------\n\n# Before\nmap_black_before <- ggplot(precincts_before) +\n  geom_sf(aes(fill = lisa_black), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"LISA Cluster\") +\n  theme_minimal() +\n  labs(\n    title = \"Black Population Clusters: BEFORE (2010 Census)\",\n    subtitle = \"Local Moran's I cluster classification\"\n  ) +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nprint(map_black_before)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-3.png)\n:::\n\n```{.r .cell-code .hidden}\n# After\nmap_black_after <- ggplot(precincts_after) +\n  geom_sf(aes(fill = lisa_black), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"LISA Cluster\") +\n  theme_minimal() +\n  labs(\n    title = \"Black Population Clusters: AFTER (2020 Census)\",\n    subtitle = \"Local Moran's I cluster classification\"\n  ) +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nprint(map_black_after)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-4.png)\n:::\n\n```{.r .cell-code .hidden}\n# --------------------------------------------\n# SIDE-BY-SIDE COMPARISON (optional but nice)\n# --------------------------------------------\n\nlibrary(patchwork)\n\n# Crime comparison\ncrime_comparison <- map_crime_before + map_crime_after +\n  plot_annotation(title = \"Crime Hot Spots: Before vs After Patternizr\")\n\nprint(crime_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-5.png)\n:::\n\n```{.r .cell-code .hidden}\n# Black population comparison\nblack_comparison <- map_black_before + map_black_after +\n  plot_annotation(title = \"Black Population Clusters: 2010 vs 2020\")\n\nprint(black_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-20-6.png)\n:::\n\n```{.r .cell-code .hidden}\n# Save maps\nggsave(\"lisa_crime_before.png\", map_crime_before, width = 8, height = 8)\nggsave(\"lisa_crime_after.png\", map_crime_after, width = 8, height = 8)\nggsave(\"lisa_black_before.png\", map_black_before, width = 8, height = 8)\nggsave(\"lisa_black_after.png\", map_black_after, width = 8, height = 8)\nggsave(\"lisa_crime_comparison.png\", crime_comparison, width = 14, height = 7)\nggsave(\"lisa_black_comparison.png\", black_comparison, width = 14, height = 7)\n\nprint(\"Maps saved!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Maps saved!\"\n```\n\n\n:::\n:::\n\n\n## Monte Carlo Null Model for Crime Clustering\n\nGlobal Moran’s \\(I\\) can be statistically significant even under modest clustering when sample sizes are large; more importantly, observed clustering may reflect population distribution rather than any additional geographic process. We therefore implement a Monte Carlo simulation under a population-proportional null:\n\n- The total number of crimes observed in a period is held fixed.\n- Crimes are randomly allocated to precincts with probability proportional to precinct population.\n- Simulated crime rates are computed and Moran’s \\(I\\) is evaluated for each simulation.\n\nLet \\(C\\) be the observed number of crimes in a period and \\(p_p = \\frac{Pop_p}{\\sum_q Pop_q}\\). A single simulation draws precinct crime counts\n\n$$\n(C_1,\\ldots,C_n) \\sim \\text{Multinomial}\\left(C; p_1,\\ldots,p_n\\right),\n$$\n\nand constructs simulated rates \\(CrimeRate_p^{(s)} = 1000 \\times \\frac{C_p}{Pop_p}\\). Repeating this process yields an empirical null distribution of Moran’s \\(I\\). We compute the Monte Carlo p-value as the proportion of simulated Moran’s \\(I\\) values greater than or equal to the observed \\(I\\) (with a standard +1 correction):\n\n$$\np = \\frac{\\#\\{I^{(s)} \\ge I^{obs}\\} + 1}{S + 1},\n$$\n\nwhere \\(S\\) is the number of simulations.\n\nMONTE CARLO SIMULATION\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nset.seed(65)\nsimulate_morans_i <- function(precincts_df, weights, n_sims = 999) {\n  \n  # Get total crimes and population\n  total_crimes <- sum(precincts_df$total_crimes)\n  populations <- precincts_df$total_pop_alloc\n  total_pop <- sum(populations)\n  \n  # Population proportions (probability of crime in each precinct under null)\n  pop_proportions <- populations / total_pop\n  \n  # Store simulated Moran's I values\n  sim_morans <- numeric(n_sims)\n  \n  # Run simulations\n  for (i in 1:n_sims) {\n    # Randomly allocate crimes proportional to population\n    # Each crime is assigned to a precinct with probability = pop proportion\n    sim_crimes <- rmultinom(1, size = total_crimes, prob = pop_proportions)[,1]\n    \n    # Calculate simulated crime rate\n    sim_rate <- (sim_crimes / populations) * 1000\n    \n    # Handle any Inf values (shouldn't happen but just in case)\n    sim_rate[is.infinite(sim_rate)] <- 0\n    \n    # Calculate Moran's I for this simulation\n    sim_moran <- moran(sim_rate, weights, n = length(sim_rate), S0 = Szero(weights))\n    sim_morans[i] <- sim_moran$I\n    \n    # Progress indicator\n    if (i %% 100 == 0) {\n      cat(\"Completed\", i, \"of\", n_sims, \"simulations\\n\")\n    }\n  }\n  \n  return(sim_morans)\n}\n```\n:::\n\n\nRUN SIMS FOR BEFORE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncat(\"\\n========== BEFORE PERIOD SIMULATION ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========== BEFORE PERIOD SIMULATION ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Observed Moran's I\nobserved_moran_before <- moran(\n  precincts_before$crime_rate, \n  weights_before, \n  n = nrow(precincts_before), \n  S0 = Szero(weights_before)\n)$I\n\ncat(\"Observed Moran's I (Before):\", round(observed_moran_before, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved Moran's I (Before): 0.2694 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Run simulation\ncat(\"Running 999 simulations under null hypothesis...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning 999 simulations under null hypothesis...\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsim_morans_before <- simulate_morans_i(precincts_before, weights_before, n_sims = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted 100 of 999 simulations\nCompleted 200 of 999 simulations\nCompleted 300 of 999 simulations\nCompleted 400 of 999 simulations\nCompleted 500 of 999 simulations\nCompleted 600 of 999 simulations\nCompleted 700 of 999 simulations\nCompleted 800 of 999 simulations\nCompleted 900 of 999 simulations\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Calculate p-value (proportion of simulated values >= observed)\np_value_before <- (sum(sim_morans_before >= observed_moran_before) + 1) / (999 + 1)\n\ncat(\"\\nSimulation Results (Before):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSimulation Results (Before):\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  Mean simulated Moran's I:\", round(mean(sim_morans_before), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean simulated Moran's I: -0.0133 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  SD simulated Moran's I:\", round(sd(sim_morans_before), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD simulated Moran's I: 0.0875 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  Observed Moran's I:\", round(observed_moran_before, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Observed Moran's I: 0.2694 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  Monte Carlo p-value:\", round(p_value_before, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Monte Carlo p-value: 0.003 \n```\n\n\n:::\n:::\n\n\nRUN SIMS FOR AFTER\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncat(\"\\n========== AFTER PERIOD SIMULATION ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========== AFTER PERIOD SIMULATION ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Observed Moran's I\nobserved_moran_after <- moran(\n  precincts_after$crime_rate, \n  weights_after, \n  n = nrow(precincts_after), \n  S0 = Szero(weights_after)\n)$I\n\ncat(\"Observed Moran's I (After):\", round(observed_moran_after, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved Moran's I (After): 0.3411 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Run simulation\ncat(\"Running 999 simulations under null hypothesis...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning 999 simulations under null hypothesis...\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsim_morans_after <- simulate_morans_i(precincts_after, weights_after, n_sims = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted 100 of 999 simulations\nCompleted 200 of 999 simulations\nCompleted 300 of 999 simulations\nCompleted 400 of 999 simulations\nCompleted 500 of 999 simulations\nCompleted 600 of 999 simulations\nCompleted 700 of 999 simulations\nCompleted 800 of 999 simulations\nCompleted 900 of 999 simulations\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Calculate p-value\np_value_after <- (sum(sim_morans_after >= observed_moran_after) + 1) / (999 + 1)\n\ncat(\"\\nSimulation Results (After):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSimulation Results (After):\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  Mean simulated Moran's I:\", round(mean(sim_morans_after), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean simulated Moran's I: -0.0135 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  SD simulated Moran's I:\", round(sd(sim_morans_after), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD simulated Moran's I: 0.0858 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  Observed Moran's I:\", round(observed_moran_after, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Observed Moran's I: 0.3411 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"  Monte Carlo p-value:\", round(p_value_after, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Monte Carlo p-value: 0.001 \n```\n\n\n:::\n:::\n\n\nvisualize histogram of sims\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Create data frame for plotting\nsim_df <- data.frame(\n  Morans_I = c(sim_morans_before, sim_morans_after),\n  Period = rep(c(\"Before (2010-2012)\", \"After (2017-2019)\"), each = 999)\n)\n\nobserved_df <- data.frame(\n  Morans_I = c(observed_moran_before, observed_moran_after),\n  Period = c(\"Before (2010-2012)\", \"After (2017-2019)\")\n)\n\n# Plot\nmonte_carlo_plot <- ggplot(sim_df, aes(x = Morans_I)) +\n  geom_histogram(bins = 50, fill = \"steelblue\", alpha = 0.7, color = \"white\") +\n  geom_vline(data = observed_df, aes(xintercept = Morans_I), \n             color = \"red\", linetype = \"dashed\", size = 1.2) +\n  facet_wrap(~Period, ncol = 1) +\n  theme_minimal() +\n  labs(\n    title = \"Monte Carlo Simulation: Crime Rate Spatial Autocorrelation\",\n    subtitle = \"Null hypothesis: Crime distributed proportionally to population\",\n    x = \"Moran's I\",\n    y = \"Frequency\",\n    caption = \"Red dashed line = Observed Moran's I\"\n  ) +\n  theme(\n    strip.text = element_text(size = 12, face = \"bold\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(monte_carlo_plot)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-24-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"monte_carlo_simulation.png\", monte_carlo_plot, width = 10, height = 8)\n```\n:::\n\n\nSUMMARY TABLE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmc_summary <- data.frame(\n  Period = c(\"Before (2010-2012)\", \"After (2017-2019)\"),\n  Observed_Morans_I = c(observed_moran_before, observed_moran_after),\n  Mean_Simulated = c(mean(sim_morans_before), mean(sim_morans_after)),\n  SD_Simulated = c(sd(sim_morans_before), sd(sim_morans_after)),\n  P_Value = c(p_value_before, p_value_after)\n)\n\nprint(\"========== MONTE CARLO SUMMARY ==========\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"========== MONTE CARLO SUMMARY ==========\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(mc_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Period Observed_Morans_I Mean_Simulated SD_Simulated P_Value\n1 Before (2010-2012)         0.2694396    -0.01333626   0.08746933   0.003\n2  After (2017-2019)         0.3410835    -0.01349132   0.08583694   0.001\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Interpretation\ncat(\"\\n========== INTERPRETATION ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========== INTERPRETATION ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nif (p_value_before < 0.05) {\n  cat(\"BEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p =\", round(p_value_before, 4), \")\\n\")\n} else {\n  cat(\"BEFORE: Fail to reject null - crime clustering is consistent with population-proportional distribution (p =\", round(p_value_before, 4), \")\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.003 )\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nif (p_value_after < 0.05) {\n  cat(\"AFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p =\", round(p_value_after, 4), \")\\n\")\n} else {\n  cat(\"AFTER: Fail to reject null - crime clustering is consistent with population-proportional distribution (p =\", round(p_value_after, 4), \")\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.001 )\n```\n\n\n:::\n:::\n\n\nThe blue histograms show what Moran's I values look like under the null hypothesis (crime distributed proportionally to population). They're centered around 0 (no spatial autocorrelation).The red dashed line is observed Moran's I - way out in the right tail for both periods.\n\nIn both periods, crime is significantly MORE clustered than we would expect if it were simply distributed proportionally to population.\n- If crime happened randomly based on where people live, we'd expect Moran's I ≈ 0\n- But we observe Moran's I of 0.27-0.34, which is far outside what we'd expect by chance\n- This means there's \"excess\" spatial clustering of crime beyond what population explains \n\n\n\"========== MONTE CARLO SUMMARY ==========\"\n              Period Observed_Morans_I Mean_Simulated SD_Simulated P_Value\n1 Before (2010-2012)         0.2694396    -0.01333626   0.08746933   0.003\n2  After (2017-2019)         0.3410835    -0.01349132   0.08583694   0.001\n\n========== INTERPRETATION ==========\nBEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.003 )\nAFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.001 )\n\n## Geographically Weighted Regression\n\nFinally, we fit geographically weighted regression (GWR) models in each period to assess spatial non-stationarity in the association between racial composition and crime rates. For precinct \\(p\\) with coordinates \\((u_p, v_p)\\), GWR estimates location-specific coefficients:\n\n$$\nCrimeRate_p = \\beta_0(u_p,v_p) + \\beta_1(u_p,v_p)\\%Black_p + \\beta_2(u_p,v_p)\\%Hispanic_p + \\beta_3(u_p,v_p)\\%White_p + \\varepsilon_p.\n$$\n\nAn adaptive bandwidth is selected via the standard GWR bandwidth selection routine, and local coefficients (particularly \\(\\beta_1(u_p,v_p)\\)) are mapped for visual comparison across periods. This component is explicitly diagnostic: changes in coefficient heterogeneity can reflect shifts in policing geography, demographic change, or other local dynamics; thus, results are interpreted as evidence of spatial variation rather than causal impact.\n\nGEOGRAPHICALLY WEIGHT REGRESSION\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# ============================================\n# SECTION 12: GEOGRAPHICALLY WEIGHTED REGRESSION\n# ============================================\n\nlibrary(spgwr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: sp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNOTE: This package does not constitute approval of GWR\nas a method of spatial analysis; see example(gwr)\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# --------------------------------------------\n# 12A: Prepare data for GWR - BEFORE period\n# --------------------------------------------\n\n# Remove any NAs and prepare sf object\nprecincts_gwr_before <- precincts_before %>%\n  filter(!is.na(crime_rate), !is.na(pct_black), !is.na(pct_hispanic), !is.na(pct_white))\n\n# Get centroids for GWR\ncoords_before <- st_coordinates(st_centroid(precincts_gwr_before))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: st_centroid assumes attributes are constant over geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Create sp object\nprecincts_sp_before <- as(precincts_gwr_before, \"Spatial\")\n\n# --------------------------------------------\n# 12B: Fit GWR - BEFORE period\n# --------------------------------------------\n\ncat(\"=== Fitting GWR for BEFORE period ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Fitting GWR for BEFORE period ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Bandwidth selection (this may take a moment)\nbw_before <- gwr.sel(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_before,\n  coords = coords_before,\n  adapt = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr.sel(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_before, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive q: 0.381966 CV score: 14999.83 \nAdaptive q: 0.618034 CV score: 15097.84 \nAdaptive q: 0.236068 CV score: 15085.6 \nAdaptive q: 0.4209454 CV score: 15005.67 \nAdaptive q: 0.382664 CV score: 15000.59 \nAdaptive q: 0.3262379 CV score: 15015.89 \nAdaptive q: 0.3606798 CV score: 15022.54 \nAdaptive q: 0.3738354 CV score: 15010.12 \nAdaptive q: 0.3788604 CV score: 15003.06 \nAdaptive q: 0.3813392 CV score: 14999.72 \nAdaptive q: 0.3815285 CV score: 14999.47 \nAdaptive q: 0.3816274 CV score: 14999.45 \nAdaptive q: 0.3816681 CV score: 14999.5 \nAdaptive q: 0.3815867 CV score: 14999.41 \nAdaptive q: 0.3815867 CV score: 14999.41 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"Optimal adaptive bandwidth (Before):\", round(bw_before, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal adaptive bandwidth (Before): 0.382 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Fit GWR model\ngwr_before <- gwr(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_before,\n  coords = coords_before,\n  adapt = bw_before,\n  hatmatrix = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_before, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(gwr_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ngwr(formula = crime_rate ~ pct_black + pct_hispanic + pct_white, \n    data = precincts_sp_before, coords = coords_before, adapt = bw_before, \n    hatmatrix = TRUE)\nKernel function: gwr.Gauss \nAdaptive quantile: 0.3815867 (about 29 of 76 data points)\nSummary of GWR coefficient estimates at data points:\n                   Min.    1st Qu.     Median    3rd Qu.       Max.  Global\nX.Intercept. 28.7125865 30.2015845 31.6285635 32.4752874 34.2351855 32.1571\npct_black     0.2328434  0.2780089  0.3176021  0.3579805  0.4033567  0.3097\npct_hispanic -0.2523239 -0.2034498 -0.1544861 -0.1023741 -0.0356422 -0.1718\npct_white    -0.1112431 -0.0608376 -0.0064229  0.0408800  0.0943873 -0.0113\nNumber of data points: 76 \nEffective number of parameters (residual: 2traceS - traceS'S): 8.473558 \nEffective degrees of freedom (residual: 2traceS - traceS'S): 67.52644 \nSigma (residual: 2traceS - traceS'S): 13.77924 \nEffective number of parameters (model: traceS): 6.733035 \nEffective degrees of freedom (model: traceS): 69.26697 \nSigma (model: traceS): 13.60501 \nSigma (ML): 12.98839 \nAICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 622.8891 \nAIC (GWR p. 96, eq. 4.22): 612.1482 \nResidual sum of squares: 12821.06 \nQuasi-global R2: 0.35847 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# --------------------------------------------\n# 12C: Prepare data for GWR - AFTER period\n# --------------------------------------------\n\nprecincts_gwr_after <- precincts_after %>%\n  filter(!is.na(crime_rate), !is.na(pct_black), !is.na(pct_hispanic), !is.na(pct_white))\n\ncoords_after <- st_coordinates(st_centroid(precincts_gwr_after))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: st_centroid assumes attributes are constant over geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprecincts_sp_after <- as(precincts_gwr_after, \"Spatial\")\n\n# --------------------------------------------\n# 12D: Fit GWR - AFTER period\n# --------------------------------------------\n\ncat(\"\\n=== Fitting GWR for AFTER period ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Fitting GWR for AFTER period ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nbw_after <- gwr.sel(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_after,\n  coords = coords_after,\n  adapt = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr.sel(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_after, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive q: 0.381966 CV score: 7859.708 \nAdaptive q: 0.618034 CV score: 8107.737 \nAdaptive q: 0.236068 CV score: 7510.614 \nAdaptive q: 0.145898 CV score: 7291.135 \nAdaptive q: 0.09016994 CV score: 6981.164 \nAdaptive q: 0.05572809 CV score: 6351.826 \nAdaptive q: 0.03444185 CV score: 5989.444 \nAdaptive q: 0.02128624 CV score: 5981.105 \nAdaptive q: 0.02719804 CV score: 6053.432 \nAdaptive q: 0.01315562 CV score: 6539.406 \nAdaptive q: 0.01818062 CV score: 6069.482 \nAdaptive q: 0.02354434 CV score: 5996.767 \nAdaptive q: 0.02009999 CV score: 5995.587 \nAdaptive q: 0.02214876 CV score: 5981.799 \nAdaptive q: 0.02083313 CV score: 5984.272 \nAdaptive q: 0.02164961 CV score: 5980.409 \nAdaptive q: 0.02160892 CV score: 5980.412 \nAdaptive q: 0.0216903 CV score: 5980.425 \nAdaptive q: 0.02164961 CV score: 5980.409 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"Optimal adaptive bandwidth (After):\", round(bw_after, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal adaptive bandwidth (After): 0.022 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngwr_after <- gwr(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_after,\n  coords = coords_after,\n  adapt = bw_after,\n  hatmatrix = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_after, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(gwr_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ngwr(formula = crime_rate ~ pct_black + pct_hispanic + pct_white, \n    data = precincts_sp_after, coords = coords_after, adapt = bw_after, \n    hatmatrix = TRUE)\nKernel function: gwr.Gauss \nAdaptive quantile: 0.02164961 (about 1 of 76 data points)\nSummary of GWR coefficient estimates at data points:\n                   Min.    1st Qu.     Median    3rd Qu.       Max. Global\nX.Intercept. -143.51155  -37.59227   -2.97766   16.48198  221.46513 3.0985\npct_black      -1.53178    0.28843    0.52178    0.89712    7.27172 0.3223\npct_hispanic   -3.41227    0.03749    0.33025    0.74175    1.51627 0.2683\npct_white      -2.59499   -0.13777    0.10581    0.36510    1.99329 0.0773\nNumber of data points: 76 \nEffective number of parameters (residual: 2traceS - traceS'S): 50.41472 \nEffective degrees of freedom (residual: 2traceS - traceS'S): 25.58528 \nSigma (residual: 2traceS - traceS'S): 5.199016 \nEffective number of parameters (model: traceS): 39.77968 \nEffective degrees of freedom (model: traceS): 36.22032 \nSigma (model: traceS): 4.369584 \nSigma (ML): 3.016542 \nAICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 564.6389 \nAIC (GWR p. 96, eq. 4.22): 423.2833 \nResidual sum of squares: 691.5642 \nQuasi-global R2: 0.9404968 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# --------------------------------------------\n# 12E: Extract and map local coefficients\n# --------------------------------------------\n\n# Extract coefficients from GWR results\ngwr_coefs_before <- as.data.frame(gwr_before$SDF)\ngwr_coefs_after <- as.data.frame(gwr_after$SDF)\n\n# Add to sf objects\nprecincts_gwr_before$gwr_pct_black <- gwr_coefs_before$pct_black\nprecincts_gwr_before$gwr_intercept <- gwr_coefs_before$`(Intercept)`\nprecincts_gwr_before$gwr_localR2 <- gwr_coefs_before$localR2\n\nprecincts_gwr_after$gwr_pct_black <- gwr_coefs_after$pct_black\nprecincts_gwr_after$gwr_intercept <- gwr_coefs_after$`(Intercept)`\nprecincts_gwr_after$gwr_localR2 <- gwr_coefs_after$localR2\n\n# --------------------------------------------\n# 12F: Map local pct_black coefficients\n# --------------------------------------------\n\n# Get consistent color scale\ncoef_range <- range(c(precincts_gwr_before$gwr_pct_black, precincts_gwr_after$gwr_pct_black))\n\ngwr_map_before <- ggplot(precincts_gwr_before) +\n  geom_sf(aes(fill = gwr_pct_black), color = \"white\", size = 0.2) +\n  scale_fill_gradient2(\n    low = \"#377EB8\",      # Blue = negative/weak effect\n    mid = \"white\",\n    high = \"#E41A1C\",     # Red = strong positive effect\n    midpoint = 0,\n    name = \"Local\\nCoefficient\",\n    limits = coef_range\n  ) +\n  theme_minimal() +\n  labs(title = \"BEFORE (2010-2012)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\ngwr_map_after <- ggplot(precincts_gwr_after) +\n  geom_sf(aes(fill = gwr_pct_black), color = \"white\", size = 0.2) +\n  scale_fill_gradient2(\n    low = \"#377EB8\",\n    mid = \"white\",\n    high = \"#E41A1C\",\n    midpoint = 0,\n    name = \"Local\\nCoefficient\",\n    limits = coef_range\n  ) +\n  theme_minimal() +\n  labs(title = \"AFTER (2017-2019)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\ngwr_comparison <- gwr_map_before + gwr_map_after +\n  plot_annotation(\n    title = \"GWR: Local Effect of % Black on Crime Rate\",\n    subtitle = \"Red = stronger positive relationship; Blue = weaker/negative relationship\"\n  )\n\nprint(gwr_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-26-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"gwr_pct_black_comparison.png\", gwr_comparison, width = 14, height = 7)\n\n# --------------------------------------------\n# 12G: Summary statistics of local coefficients\n# --------------------------------------------\n\ncat(\"\\n=== GWR Local Coefficient Summary: pct_black ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== GWR Local Coefficient Summary: pct_black ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"\\nBEFORE period:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBEFORE period:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_gwr_before$gwr_pct_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.2328  0.2780  0.3176  0.3183  0.3580  0.4034 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"\\nAFTER period:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAFTER period:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(summary(precincts_gwr_after$gwr_pct_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-1.5318  0.2884  0.5218  0.9767  0.8971  7.2717 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# --------------------------------------------\n# 12H: Map local R-squared (model fit)\n# --------------------------------------------\n\nr2_range <- range(c(precincts_gwr_before$gwr_localR2, precincts_gwr_after$gwr_localR2))\n\nr2_map_before <- ggplot(precincts_gwr_before) +\n  geom_sf(aes(fill = gwr_localR2), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    name = \"Local R²\",\n    limits = r2_range\n  ) +\n  theme_minimal() +\n  labs(title = \"BEFORE (2010-2012)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nr2_map_after <- ggplot(precincts_gwr_after) +\n  geom_sf(aes(fill = gwr_localR2), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    name = \"Local R²\",\n    limits = r2_range\n  ) +\n  theme_minimal() +\n  labs(title = \"AFTER (2017-2019)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nr2_comparison <- r2_map_before + r2_map_after +\n  plot_annotation(\n    title = \"GWR: Local Model Fit (R²)\",\n    subtitle = \"Higher = demographics explain more crime variation in that area\"\n  )\n\nprint(r2_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-26-2.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"gwr_localR2_comparison.png\", r2_comparison, width = 14, height = 7)\n\ncat(\"\\n=== GWR ANALYSIS COMPLETE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== GWR ANALYSIS COMPLETE ===\n```\n\n\n:::\n:::\n\n\n# Results\n\n## Global Spatial Autocorrelation\n\nAcross both periods, violent crime rates exhibit statistically significant positive spatial autocorrelation. Prior to Patternizr, the Global Moran’s I for precinct-level crime rates was 0.269, indicating moderate clustering of high- and low-crime precincts. In the post-Patternizr period, this value increased to 0.341, reflecting a strengthening of spatial concentration in recorded violent crime.\n\nBy contrast, the spatial autocorrelation of racial composition—measured as the percentage of Black residents per precinct—was substantially higher than that of crime in both periods, with Moran’s I values of 0.570 (2010–2012) and 0.558 (2017–2019). These magnitudes indicate strong and persistent spatial clustering of racial composition across New York City precincts, consistent with long-standing patterns of residential segregation. Importantly, the degree of racial clustering remained effectively stable across periods, declining only marginally.\n\nTaken together, these results indicate a divergence in spatial dynamics: while racial composition remained highly clustered and largely unchanged, crime became more spatially concentrated in the post-Patternizr period.\n\n## Local Spatial Clustering and High–High Precincts\n\nLocal Indicators of Spatial Association (LISA) reveal further distinctions between periods. Before Patternizr, six precincts were classified as High–High crime clusters—precincts with elevated crime rates surrounded by similarly high-crime neighbors. This number declined to four precincts in the post-Patternizr period, suggesting a modest reduction in the number of statistically significant crime hot spots.\n\nSimilarly, the number of High–High Black population clusters decreased slightly from seven precincts before Patternizr to six afterward. This change is small in magnitude and aligns with the largely stable global Moran’s I values for racial composition.\n\nCrucially, however, the overlap between High–High crime clusters and High–High Black population clusters changed dramatically. In the pre-Patternizr period, three precincts simultaneously exhibited statistically significant clustering for both high crime rates and high Black population share. In the post-Patternizr period, this overlap fell to zero. No precincts were classified as High–High for both crime and Black population after Patternizr implementation.\n\n## Monte Carlo Simulation Results\n\nMonte Carlo simulations provide additional evidence that the observed spatial clustering of crime is not solely a function of population distribution. Under a null model in which crimes are allocated proportionally to precinct population, the probability of observing Moran’s I values as large as those measured is extremely low in both periods. The resulting p-values are 0.003 for the pre-Patternizr period and 0.001 for the post-Patternizr period.\n\nThese findings indicate that crime is significantly more spatially clustered than would be expected if incidents were distributed randomly according to population alone. Moreover, the lower p-value in the post-Patternizr period is consistent with the observed increase in global crime clustering.\n\n## Interpretation\n\nThe results point to a nuanced and potentially consequential shift in the spatial relationship between crime, race, and geography following the implementation of Patternizr. While racial composition remained highly segregated across precincts, the spatial clustering of crime intensified. At the same time, the direct geographic overlap between predominantly Black precincts and crime hot spots disappeared.\n\nOne interpretation of this pattern is that predictive policing practices may have altered the geographic focus of enforcement and crime detection, concentrating recorded crime into fewer, more spatially cohesive areas that are no longer disproportionately concentrated in predominantly Black precincts. Under this interpretation, the reduction in overlap could be viewed as evidence of a decoupling between racial composition and spatial crime hot spots.\n\nHowever, alternative explanations must also be considered. Demographic changes—particularly gentrification and population turnover between 2010 and 2020—may have reduced the Black population share in historically high-crime precincts, thereby eliminating overlap without fundamentally changing underlying policing dynamics. Additionally, changes in reporting practices or enforcement priorities could have shifted where crimes are recorded rather than where they occur.\n\nWhat can be stated with confidence is that the spatial structure of crime changed more substantially than the spatial structure of race. The increase in crime clustering alongside stable racial clustering suggests that post-Patternizr crime patterns became more geographically concentrated but less directly aligned with historically segregated Black neighborhoods. This divergence underscores the importance of spatially explicit analyses when evaluating claims of racial bias in predictive policing systems and cautions against interpretations based solely on global or non-spatial statistics.\n\n## Geographically Weighted Regression\n\nTo probe whether the association between precinct racial composition and violent felony rates is spatially stationary, we fit geographically weighted regression (GWR) models in each period with crime rate as the dependent variable and precinct racial composition (% Black, % Hispanic, % White) as covariates. GWR results indicate a substantial change in the locality and heterogeneity of these relationships between the pre-Patternizr and post-Patternizr periods.\n\nIn the pre-Patternizr period (2010–2012), the optimal adaptive bandwidth selected by cross-validation was relatively large ( q≈0.382, approximately 29 of 76 data points contributing to each local fit). This implies that the estimated relationships are comparatively smooth across space, with local coefficients borrowing information from a broad neighborhood. Consistent with this, the local coefficient for %Black is uniformly positive and tightly distributed across precincts (min = 0.2328, median = 0.3176, max = 0.4034; mean = 0.3183). The corresponding global coefficient for %Black is similarly positive (0.3097). In substantive terms, the direction of association between Black population share and crime rate is stable across the city in this period: precincts with higher Black population percentages tend to exhibit higher violent felony rates, and this association varies only modestly across precincts.\n\nBy contrast, in the post-Patternizr period (2017–2019), the selected bandwidth shrinks dramatically (\n$q≈0.022$, approximately 1 of 76 data points contributing to each local fit). This extremely localized bandwidth implies that the relationship between demographic composition and crime rates is no longer well-characterized by broad regional smoothness and instead varies sharply at fine spatial scales. Correspondingly, the distribution of the local\n%Black coefficients becomes both wider and qualitatively different: coefficients range from negative values (min $= −1.5318$) to very large positive values (max = 7.2717), with a median of 0.5218 and a markedly higher mean (0.9767). The global coefficient remains positive (0.3223), but the local estimates indicate that this global relationship conceals substantial spatial non-stationarity—some precincts exhibit weak or even negative local associations, while others exhibit very strong positive relationships.\n\nModel fit metrics reinforce the contrast between periods. The quasi-global $R^2$ for the pre-period GWR is 0.3585, indicating that demographic covariates explain a moderate fraction of precinct-level variation in violent felony rates when allowing coefficients to vary over space. In the post-period, the quasi-global $R^2$ \nincreases sharply to 0.9405. While this suggests an apparently much stronger explanatory relationship between demographics and crime rates in the later period, this result must be interpreted cautiously given the extremely small bandwidth and the corresponding effective number of parameters (approximately 39.8 in the post-period versus 6.7 in the pre-period), which indicates far greater model flexibility. In other words, the large increase in quasi-global $R^2$ is consistent with a substantially more localized and potentially more complex spatial relationship, but it may also reflect the propensity of highly localized GWR specifications to capture idiosyncratic local variation.\n\nTaken together, the GWR results support a central descriptive conclusion: the race–crime relationship becomes substantially more spatially heterogeneous in the post-Patternizr period. Before Patternizr, the positive association between%Black and crime rate is comparatively consistent across precincts, as reflected in both the large bandwidth and the narrow range of local coefficients. After Patternizr, local coefficients vary dramatically in magnitude and even sign, indicating that the relationship is not uniform across New York City. This pattern aligns with the broader spatial findings reported above: global crime clustering increases even as the direct overlap between High–High crime clusters and High–High Black clusters disappears. In combination, these results suggest that post-period dynamics are characterized less by a single citywide race–crime gradient and more by localized, place-specific relationships that differ substantially across precincts.\n\nFINAL VISUALIZATIONS TO USE\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(ggplot2)\nlibrary(patchwork)\n\n#choloropleth maps of CRIME before/after\n# Set consistent scale for comparison\ncrime_rate_range <- range(c(precincts_before$crime_rate, precincts_after$crime_rate))\n\nmap_rate_before <- ggplot(precincts_before) +\n  geom_sf(aes(fill = crime_rate), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    name = \"Crime Rate\\n(per 1,000)\",\n    limits = crime_rate_range\n  ) +\n  theme_minimal() +\n  labs(title = \"BEFORE Patternizr (2010-2012)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nmap_rate_after <- ggplot(precincts_after) +\n  geom_sf(aes(fill = crime_rate), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    name = \"Crime Rate\\n(per 1,000)\",\n    limits = crime_rate_range\n  ) +\n  theme_minimal() +\n  labs(title = \"AFTER Patternizr (2017-2019)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\ncrime_rate_comparison <- map_rate_before + map_rate_after +\n  plot_annotation(\n    title = \"Violent Felony Rates by NYPD Precinct\",\n    subtitle = \"Before and After Patternizr Implementation\"\n  )\n\nprint(crime_rate_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-27-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"crime_rate_comparison.png\", crime_rate_comparison, width = 14, height = 7)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#chloropleth maps black pct BEFORE and AFTER\n\npct_black_range <- range(c(precincts_before$pct_black, precincts_after$pct_black))\n\nmap_black_before <- ggplot(precincts_before) +\n  geom_sf(aes(fill = pct_black), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    option = \"magma\",\n    name = \"% Black\",\n    limits = pct_black_range\n  ) +\n  theme_minimal() +\n  labs(title = \"2010 Census\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nmap_black_after <- ggplot(precincts_after) +\n  geom_sf(aes(fill = pct_black), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    option = \"magma\",\n    name = \"% Black\",\n    limits = pct_black_range\n  ) +\n  theme_minimal() +\n  labs(title = \"2020 Census\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\npct_black_comparison <- map_black_before + map_black_after +\n  plot_annotation(\n    title = \"Black Population by NYPD Precinct\",\n    subtitle = \"Demographic Change 2010-2020\"\n  )\n\nprint(pct_black_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-28-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"pct_black_comparison.png\", pct_black_comparison, width = 14, height = 7)\n```\n:::\n\n\nLISA MAPS SIDE BY SIDE - CRIME\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlisa_colors <- c(\n  \"High-High\" = \"#E41A1C\",\n  \"Low-Low\" = \"#377EB8\",\n  \"High-Low\" = \"#FF7F00\",\n  \"Low-High\" = \"#984EA3\",\n  \"Not Significant\" = \"#D3D3D3\"\n)\n\nlisa_crime_before <- ggplot(precincts_before) +\n  geom_sf(aes(fill = lisa_crime), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"Cluster Type\") +\n  theme_minimal() +\n  labs(title = \"BEFORE (2010-2012)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nlisa_crime_after <- ggplot(precincts_after) +\n  geom_sf(aes(fill = lisa_crime), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"Cluster Type\") +\n  theme_minimal() +\n  labs(title = \"AFTER (2017-2019)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nlisa_crime_comparison <- lisa_crime_before + lisa_crime_after +\n  plot_annotation(\n    title = \"Crime Rate Hot Spots (LISA Clusters)\",\n    subtitle = \"Red = High-High clusters (hot spots)\"\n  )\n\nprint(lisa_crime_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-29-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"lisa_crime_comparison.png\", lisa_crime_comparison, width = 14, height = 7)\n```\n:::\n\n\nLISA MAPS SIDE BY SIDE - BLACK PCT\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlisa_black_before <- ggplot(precincts_before) +\n  geom_sf(aes(fill = lisa_black), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"Cluster Type\") +\n  theme_minimal() +\n  labs(title = \"2010 Census\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nlisa_black_after <- ggplot(precincts_after) +\n  geom_sf(aes(fill = lisa_black), color = \"white\", size = 0.2) +\n  scale_fill_manual(values = lisa_colors, name = \"Cluster Type\") +\n  theme_minimal() +\n  labs(title = \"2020 Census\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nlisa_black_comparison <- lisa_black_before + lisa_black_after +\n  plot_annotation(\n    title = \"Black Population Clusters (LISA)\",\n    subtitle = \"Red = High-High clusters\"\n  )\n\nprint(lisa_black_comparison)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-30-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"lisa_black_comparison.png\", lisa_black_comparison, width = 14, height = 7)\n```\n:::\n\n\nSCATTER PLOT CRIME VS. PCT BLACK\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Combine data for plotting\nscatter_before <- precincts_before %>%\n  st_drop_geometry() %>%\n  select(precinct, crime_rate, pct_black) %>%\n  mutate(Period = \"Before (2010-2012)\")\n\nscatter_after <- precincts_after %>%\n  st_drop_geometry() %>%\n  select(precinct, crime_rate, pct_black) %>%\n  mutate(Period = \"After (2017-2019)\")\n\nscatter_data <- bind_rows(scatter_before, scatter_after)\n\nscatter_plot <- ggplot(scatter_data, aes(x = pct_black, y = crime_rate, color = Period)) +\n  geom_point(alpha = 0.6, size = 3) +\n  geom_smooth(method = \"lm\", se = TRUE, alpha = 0.2) +\n  scale_color_manual(values = c(\"Before (2010-2012)\" = \"#E41A1C\", \"After (2017-2019)\" = \"#377EB8\")) +\n  theme_minimal() +\n  labs(\n    title = \"Crime Rate vs. Black Population by Precinct\",\n    subtitle = \"Before and After Patternizr\",\n    x = \"% Black Population\",\n    y = \"Crime Rate (per 1,000 residents)\"\n  )\n\nprint(scatter_plot)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-31-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"scatter_crime_vs_black.png\", scatter_plot, width = 10, height = 7)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n:::\n\n\nBoth lines slope upward → precincts with higher Black populations tend to have higher crime rates. This is the core pattern your hypothesis is about.\n\nThe relationship is STEEPER in the \"Before\" period.\n\nCrime rates dropped overall - The blue dots are generally lower than the red dots at any given % Black level. This matches what we saw earlier - crime decreased across NYC.\n\nThe red dot at ~115 crime rate with low Black % is Precinct 14 (Midtown South) - a commercial area with low residential population but lots of crime. Similar pattern to Central Park but not as extreme.\n\nTAKEAWAY: The flattening of the slope from Before to After suggests that the race-crime relationship weakened over time. This is consistent with your LISA finding that the overlap between crime hot spots and Black population hot spots disappeared.\n\nMORANS I COMPARISON BAR CHART\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmoran_plot_data <- data.frame(\n  Variable = c(\"Crime Rate\", \"Crime Rate\", \"% Black\", \"% Black\"),\n  Period = c(\"Before\", \"After\", \"Before\", \"After\"),\n  Morans_I = c(0.269, 0.341, 0.570, 0.558)\n)\n\nmoran_plot_data$Period <- factor(moran_plot_data$Period, levels = c(\"Before\", \"After\"))\n\nmoran_bar <- ggplot(moran_plot_data, aes(x = Variable, y = Morans_I, fill = Period)) +\n  geom_bar(stat = \"identity\", position = \"dodge\", width = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  scale_fill_manual(values = c(\"Before\" = \"#E41A1C\", \"After\" = \"#377EB8\")) +\n  theme_minimal() +\n  labs(\n    title = \"Spatial Autocorrelation: Before vs After Patternizr\",\n    subtitle = \"Global Moran's I (higher = more clustered)\",\n    x = \"\",\n    y = \"Moran's I\"\n  ) +\n  ylim(0, 0.7)\n\nprint(moran_bar)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-jats/unnamed-chunk-32-1.png)\n:::\n\n```{.r .cell-code .hidden}\nggsave(\"morans_i_comparison.png\", moran_bar, width = 8, height = 6)\n```\n:::\n\n\nSUMMARY RESULTS\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nresults_table <- data.frame(\n  Metric = c(\n    \"Crime Rate Moran's I\",\n    \"Crime Rate Moran's I\",\n    \"% Black Moran's I\",\n    \"% Black Moran's I\",\n    \"Crime High-High Clusters\",\n    \"Crime High-High Clusters\",\n    \"Black High-High Clusters\",\n    \"Black High-High Clusters\",\n    \"Overlapping High-High\",\n    \"Overlapping High-High\",\n    \"Monte Carlo p-value\",\n    \"Monte Carlo p-value\"\n  ),\n  Period = rep(c(\"Before (2010-2012)\", \"After (2017-2019)\"), 6),\n  Value = c(\n    \"0.269\", \"0.341\",\n    \"0.570\", \"0.558\",\n    \"6 precincts\", \"4 precincts\",\n    \"7 precincts\", \"6 precincts\",\n    \"3 precincts\", \"0 precincts\",\n    \"0.003\", \"0.001\"\n  )\n)\n\nprint(\"========== SUMMARY RESULTS TABLE ==========\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"========== SUMMARY RESULTS TABLE ==========\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(results_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Metric             Period       Value\n1      Crime Rate Moran's I Before (2010-2012)       0.269\n2      Crime Rate Moran's I  After (2017-2019)       0.341\n3         % Black Moran's I Before (2010-2012)       0.570\n4         % Black Moran's I  After (2017-2019)       0.558\n5  Crime High-High Clusters Before (2010-2012) 6 precincts\n6  Crime High-High Clusters  After (2017-2019) 4 precincts\n7  Black High-High Clusters Before (2010-2012) 7 precincts\n8  Black High-High Clusters  After (2017-2019) 6 precincts\n9     Overlapping High-High Before (2010-2012) 3 precincts\n10    Overlapping High-High  After (2017-2019) 0 precincts\n11      Monte Carlo p-value Before (2010-2012)       0.003\n12      Monte Carlo p-value  After (2017-2019)       0.001\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Save as CSV for easy inclusion in paper\nwrite.csv(results_table, \"results_summary.csv\", row.names = FALSE)\n\nprint(\"\\n========== ALL VISUALIZATIONS SAVED ==========\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"\\n========== ALL VISUALIZATIONS SAVED ==========\"\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "index_files/figure-jats"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}