{
  "hash": "001c6a7a804965986442d4de13ec1ec7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Examining Claims of Racial Bias in Predictive Policing through a Geographic Perspective\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show code\"\nauthors:\n  - name: Fareeza Ali and Jackson Howes\n    affiliation: Georgetown University\n    corresponding: true\nbibliography: references.bib\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n## Abstract\n\nPredictive policing systems have been repeatedly criticized for reproducing and amplifying racial disparities, yet empirical evaluation is complicated by the fact that \"crime data\" are not neutral measurements of underlying criminal behavior but administrative records produced through enforcement, reporting, and institutional decision-making. In this manuscript, we assess whether spatial patterns in recorded violent felony incidents changed in ways consistent with the claim that algorithmic policing intensified racially disparate enforcement. We adopt a geographic perspective, using NYPD precincts as the unit of analysis, violent felony complaint records as the outcome, and census-derived racial composition as the principal demographic covariate. Our design compares a pre-period (2010–2012) and a post-period (2013–2019) bracketing the implementation window of Patternizr, a predictive policing system introduced by the NYPD in 2013. We quantify global spatial autocorrelation in both crime rates and Black population share using Moran's $I$, identify local clusters using Local Indicators of Spatial Association (LISA), and assess whether observed clustering exceeds what would be expected under a population-proportional null model via Monte Carlo simulation. Finally, we use geographically weighted regression (GWR) to examine whether the relationship between racial composition and recorded crime rates became more spatially heterogeneous over time. We emphasize throughout that any observed differences are associational rather than causal, given concurrent neighborhood change and other confounds; nonetheless, this framework isolates concrete spatial signatures that are directly relevant to claims of algorithmically mediated bias.\n\n## Introduction\n\nPublic and scholarly debates over predictive policing have increasingly centered on a shared concern: that algorithmic systems trained on historically patterned enforcement data may re-entrench and intensify the very disparities they purport to mitigate. In the specific context of New York City, Patternizr has been described as a tool intended to assist in recognizing potentially related crime patterns; however, even systems framed as investigative aids may shape enforcement attention and thereby the geography of recorded crime. When police deploy resources unevenly across space, administrative \"crime\" data can reflect both underlying incidents and the spatial distribution of policing itself. As a result, testing claims of algorithmic bias requires methodological approaches that can separate (or at minimum, describe) changes in spatial concentration and demographic overlap.\n\nWe therefore pose a geographically grounded question: did the spatial structure of recorded violent felony crime become more clustered after the implementation of Patternizr, and did the geography of those clusters align differently with the geography of Black residential concentration? Importantly, our inferential target is not a direct causal estimate of Patternizr's effect. Instead, we evaluate whether the *spatial signatures* of recorded crime—global clustering, local hot spots, and hot-spot overlap with racially concentrated precincts—changed in ways that are consistent with common critiques of predictive policing. We explicitly treat demographic change, including gentrification and population redistribution between 2010 and 2020, as a major confound that must be described alongside any policing-related interpretation.\n\n## Research Questions and Hypotheses\n\nOur analysis is organized around three primary research questions.\n\n1. **Did the spatial clustering of violent felony *crime rates* change between the pre-Patternizr and post-Patternizr periods?**\n   If predictive policing concentrated enforcement attention into a narrower set of precincts, we would expect increased spatial autocorrelation in recorded crime rates. This motivates comparison of global Moran's $I$ for precinct-level crime rates across periods.\n\n2. **Did the spatial clustering of Black residential concentration change over the same window, and how does it relate to crime clustering?**\n   Racial residential segregation produces strong spatial autocorrelation in demographic composition. If this structure is stable while crime clustering changes, then changes in the *relationship* between demographic clustering and crime clustering become substantively interpretable.\n\n3. **Did the overlap between crime hot spots and Black population hot spots change?**\n   We operationalize \"hot spot\" using LISA High–High clusters. A reduction in overlap may indicate either (i) a weakening association between racial concentration and recorded crime hot spots, or (ii) demographic change in the precincts that previously occupied both categories.\n\nIn addition, we use geographically weighted regression (GWR) as a diagnostic to evaluate whether the local association between percent Black and precinct crime rates became more spatially heterogeneous over time. Substantively, a shift toward stronger spatial non-stationarity is consistent with a more localized policing geography, but this pattern can also arise from localized neighborhood change and other place-specific dynamics.\n\n## Data and Study Design\n\n### Setup and Load Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: setup-libraries\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup-libraries\n\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLinking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup-libraries\n\nlibrary(tidycensus)\nlibrary(tigris)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTo enable caching of data, set `options(tigris_use_cache = TRUE)`\nin your R script or .Rprofile.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup-libraries\n\nlibrary(spdep)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: spData\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup-libraries\n\nlibrary(patchwork)\n\noptions(tigris_use_cache = TRUE)\noptions(tigris_progress = FALSE)\n```\n:::\n\n\n### Spatial Units and Coordinate Systems\n\nThe unit of analysis is each NYPD precinct. We load an official precinct boundary shapefile and project it to an equal-area / planar coordinate system appropriate for spatial operations (EPSG:32118). All spatial overlays and neighborhood constructions (contiguity weights) are conducted in this projected CRS to ensure that area calculations and adjacency relationships are well-defined.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: load-precincts\n\nprecincts <- st_read(\"../data/nyc_precincts.geojson\", quiet = TRUE)\nprecincts_proj <- st_transform(precincts, 32118)\n```\n:::\n\n\n### Demographic Data: Census Blocks to Precincts via Areal Interpolation\n\nBecause precinct boundaries do not align with census block boundaries, we construct precinct-level demographics using areal interpolation. Specifically, we obtain census block geometries and block-level decennial census counts for 2010 and 2020. For each census year, we intersect census blocks with precinct polygons, compute the proportion of each block's area contained within each precinct, and allocate block-level counts proportionally to those intersection weights. Summing the allocated counts across intersections yields precinct-level demographic totals.\n\nFormally, let $b$ index census blocks and $p$ index precincts. Define the intersection area $A_{bp} = \\text{area}(b \\cap p)$ and block area $A_b = \\text{area}(b)$. The areal weight is:\n\n$$\nw_{bp} = \\frac{A_{bp}}{A_b}\n$$\n\nFor a block-level count $X_b$ (e.g., total population, race counts), the precinct-allocated contribution from block $b$ is:\n\n$$\nX_{bp}^{\\text{alloc}} = w_{bp} X_b\n$$\n\nand the precinct-level total is:\n\n$$\nX_p = \\sum_{b} X_{bp}^{\\text{alloc}}\n$$\n\nWe then compute precinct demographic shares (e.g., percent Black) as:\n\n$$\n\\%Black_p = 100 \\times \\frac{Black_p}{TotalPop_p}\n$$\n\nwith analogous definitions for percent Hispanic and percent White.\n\nThis approach implicitly assumes uniform population density within each block. While imperfect, it is standard practice when translating census counts to non-nested administrative boundaries, and it produces internally consistent precinct-level denominators for per-capita crime rate computation.\n\n#### 2020 Census Data Processing\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: process-2020-census\n\n# Load 2020 block geometries\nblocks_2020 <- st_read(\"../data/tl_2020_36_tabblock20/tl_2020_36_tabblock20.shp\", quiet = TRUE)\n\nnyc_counties <- c(\"005\", \"047\", \"061\", \"081\", \"085\")\nblocks_2020_nyc <- blocks_2020 %>%\n  filter(COUNTYFP20 %in% nyc_counties)\n\n# Pull 2020 census data\np1_2020 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P1_001N\", \"P1_003N\", \"P1_004N\", \"P1_005N\", \n                \"P1_006N\", \"P1_007N\", \"P1_008N\", \"P1_009N\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2020,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2020 decennial Census\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing the PL 94-171 Redistricting Data Summary File\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNote: 2020 decennial Census data use differential privacy, a technique that\nintroduces errors into data to preserve respondent confidentiality.\nℹ Small counts should be interpreted with caution.\nℹ See https://www.census.gov/library/fact-sheets/2021/protecting-the-confidentiality-of-the-2020-census-redistricting-data.html for additional guidance.\nThis message is displayed once per session.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2020-census\n\np2_2020 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P2_001N\", \"P2_002N\", \"P2_003N\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2020,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2020 decennial Census\nUsing the PL 94-171 Redistricting Data Summary File\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2020-census\n\n# Join and interpolate 2020 data to precincts\np1_2020 <- p1_2020 %>% rename(GEOID20 = GEOID)\np2_2020 <- p2_2020 %>% rename(GEOID20 = GEOID)\n\nblocks_demo_2020 <- blocks_2020_nyc %>%\n  left_join(p1_2020, by = \"GEOID20\") %>%\n  left_join(p2_2020, by = \"GEOID20\")\n\nblocks_2020_proj <- st_transform(blocks_demo_2020, 32118)\nblocks_2020_proj <- blocks_2020_proj %>%\n  mutate(block_area = st_area(geometry))\n\nblock_precinct_int_2020 <- st_intersection(blocks_2020_proj, precincts_proj)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: attribute variables are assumed to be spatially constant throughout\nall geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2020-census\n\nblock_precinct_int_2020 <- block_precinct_int_2020 %>%\n  mutate(\n    piece_area = st_area(geometry),\n    weight = as.numeric(piece_area / block_area)\n  )\n\ndemo_vars_2020 <- c(\"P1_001N\", \"P1_003N\", \"P1_004N\", \"P1_005N\",\n                    \"P1_006N\", \"P1_007N\", \"P1_008N\", \"P1_009N\",\n                    \"P2_001N\", \"P2_002N\", \"P2_003N\")\n\nfor (v in demo_vars_2020) {\n  block_precinct_int_2020[[paste0(v, \"_alloc\")]] <-\n    block_precinct_int_2020[[v]] * block_precinct_int_2020$weight\n}\n\nprecinct_demographics_2020 <- block_precinct_int_2020 %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(across(ends_with(\"_alloc\"), sum, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There was 1 warning in `summarise()`.\nℹ In argument: `across(ends_with(\"_alloc\"), sum, na.rm = TRUE)`.\nℹ In group 1: `precinct = \"1\"`.\nCaused by warning:\n! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.\nSupply arguments directly to `.fns` through an anonymous function instead.\n\n  # Previously\n  across(a:b, mean, na.rm = TRUE)\n\n  # Now\n  across(a:b, \\(x) mean(x, na.rm = TRUE))\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2020-census\n\nprecincts_2020 <- precincts_proj %>%\n  left_join(precinct_demographics_2020, by = \"precinct\")\n```\n:::\n\n\n#### 2010 Census Data Processing\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: process-2010-census\n\n# Load 2010 block geometries\nblocks_2010 <- blocks(state = \"NY\", county = nyc_counties, year = 2010)\nblocks_2010_nyc <- blocks_2010 %>%\n  filter(COUNTYFP10 %in% nyc_counties)\n\n# Pull 2010 census data\np1_2010 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P003001\", \"P003002\", \"P003003\", \"P003004\",\n                \"P003005\", \"P003006\", \"P003007\", \"P003008\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2010,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2010 decennial Census\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing Census Summary File 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2010-census\n\np2_2010 <- get_decennial(\n  geography = \"block\",\n  variables = c(\"P004001\", \"P004002\", \"P004003\"),\n  state = \"NY\",\n  county = nyc_counties,\n  year = 2010,\n  output = \"wide\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting data from the 2010 decennial Census\nUsing Census Summary File 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2010-census\n\n# Join and interpolate 2010 data to precincts\np1_2010 <- p1_2010 %>% rename(GEOID10 = GEOID)\np2_2010 <- p2_2010 %>% rename(GEOID10 = GEOID)\n\nblocks_demo_2010 <- blocks_2010_nyc %>%\n  left_join(p1_2010, by = \"GEOID10\") %>%\n  left_join(p2_2010, by = \"GEOID10\")\n\nblocks_2010_proj <- st_transform(blocks_demo_2010, 32118)\nblocks_2010_proj <- blocks_2010_proj %>%\n  mutate(block_area = st_area(geometry))\n\nblock_precinct_int_2010 <- st_intersection(blocks_2010_proj, precincts_proj)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: attribute variables are assumed to be spatially constant throughout\nall geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: process-2010-census\n\nblock_precinct_int_2010 <- block_precinct_int_2010 %>%\n  mutate(\n    piece_area = st_area(geometry),\n    weight = as.numeric(piece_area / block_area)\n  )\n\ndemo_vars_2010 <- c(\"P003001\", \"P003002\", \"P003003\", \"P003004\",\n                    \"P003005\", \"P003006\", \"P003007\", \"P003008\",\n                    \"P004001\", \"P004002\", \"P004003\")\n\nfor (v in demo_vars_2010) {\n  block_precinct_int_2010[[paste0(v, \"_alloc\")]] <-\n    block_precinct_int_2010[[v]] * block_precinct_int_2010$weight\n}\n\nprecinct_demographics_2010 <- block_precinct_int_2010 %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(across(ends_with(\"_alloc\"), sum, na.rm = TRUE))\n\nprecincts_2010 <- precincts_proj %>%\n  left_join(precinct_demographics_2010, by = \"precinct\")\n```\n:::\n\n\n#### Standardize Column Names\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: standardize-columns\n\nprecincts_2010 <- precincts_2010 %>%\n  rename(\n    total_pop_alloc = P003001_alloc,\n    white_alloc = P003002_alloc,\n    black_alloc = P003003_alloc,\n    aian_alloc = P003004_alloc,\n    asian_alloc = P003005_alloc,\n    nhpi_alloc = P003006_alloc,\n    other_alloc = P003007_alloc,\n    two_or_more_alloc = P003008_alloc,\n    hispanic_total_alloc = P004001_alloc,\n    hispanic_alloc = P004002_alloc,\n    not_hispanic_alloc = P004003_alloc\n  )\n\nprecincts_2020 <- precincts_2020 %>%\n  rename(\n    total_pop_alloc = P1_001N_alloc,\n    white_alloc = P1_003N_alloc,\n    black_alloc = P1_004N_alloc,\n    aian_alloc = P1_005N_alloc,\n    asian_alloc = P1_006N_alloc,\n    nhpi_alloc = P1_007N_alloc,\n    other_alloc = P1_008N_alloc,\n    two_or_more_alloc = P1_009N_alloc,\n    hispanic_total_alloc = P2_001N_alloc,\n    hispanic_alloc = P2_002N_alloc,\n    not_hispanic_alloc = P2_003N_alloc\n  )\n```\n:::\n\n\n### Crime Data: Violent Felony Complaint Records\n\nWe load a cleaned violent felony complaint dataset from the city containing point locations (latitude/longitude) and complaint dates. Complaint points are converted into an `sf` point object in WGS84 (EPSG:4326) and then filtered to a bounding box corresponding to New York City to remove obvious geocoding errors. Points are subsequently projected into EPSG:32118 for spatial joins and distance-consistent operations. Complaint dates are parsed to extract year, enabling period-based subsetting.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: load-crime-data\n\nviolent_crimes <- read.csv(\"../data/violent_felony_cleaned_13.csv\")\n\nviolent_sf <- st_as_sf(\n  violent_crimes,\n  coords = c(\"long\", \"lat\"),\n  crs = 4326\n)\n\nviolent_sf <- violent_sf %>%\n  filter(\n    !is.na(geometry),\n    sf::st_coordinates(geometry)[, 1] > -74.5,\n    sf::st_coordinates(geometry)[, 1] < -73.7,\n    sf::st_coordinates(geometry)[, 2] > 40.45,\n    sf::st_coordinates(geometry)[, 2] < 40.95\n  )\n\nviolent_proj <- st_transform(violent_sf, 32118)\n\nviolent_proj <- violent_proj %>%\n  mutate(\n    complaint_date = as.Date(complaint_date),\n    year = as.integer(format(complaint_date, \"%Y\"))\n  )\n```\n:::\n\n\n### Pre/Post Comparison Windows\n\nTo reduce transitional ambiguity surrounding the implementation timeline, we define two non-overlapping windows:\n\n- **Before**: 2010–2012\n- **After**: 2013–2019\n\nFor each period, we spatially join complaint points to precinct polygons, count incidents per precinct, and compute the precinct-level violent felony rate per 1,000 residents:\n\n$$\nCrimeRate_p = 1000 \\times \\frac{Crimes_p}{TotalPop_p}\n$$\n\nWe exclude precinct 22 (Central Park) due to its negligible residential population, which otherwise induces artificially inflated per-capita rates and undermines interpretability.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: create-before-after-datasets\n\n# Filter crimes by period\ncrimes_before <- violent_proj %>% filter(year >= 2010 & year <= 2012)\ncrimes_after <- violent_proj %>% filter(year >= 2013 & year <= 2019)\n\ncat(\"Crimes before (2010-2012):\", nrow(crimes_before), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCrimes before (2010-2012): 201231 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-before-after-datasets\n\ncat(\"Crimes after (2013-2019):\", nrow(crimes_after), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCrimes after (2013-2019): 412321 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-before-after-datasets\n\n# Count crimes per precinct - BEFORE\ncrime_counts_before <- crimes_before %>%\n  st_join(precincts_proj, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(total_crimes = n(), .groups = \"drop\")\n\nprecincts_before <- precincts_2010 %>%\n  left_join(crime_counts_before, by = \"precinct\") %>%\n  mutate(\n    total_crimes = replace_na(total_crimes, 0),\n    crime_rate = (total_crimes / total_pop_alloc) * 1000,\n    pct_black = (black_alloc / total_pop_alloc) * 100,\n    pct_hispanic = (hispanic_alloc / total_pop_alloc) * 100,\n    pct_white = (white_alloc / total_pop_alloc) * 100\n  )\n\n# Count crimes per precinct - AFTER\ncrime_counts_after <- crimes_after %>%\n  st_join(precincts_proj, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(precinct) %>%\n  summarise(total_crimes = n(), .groups = \"drop\")\n\nprecincts_after <- precincts_2020 %>%\n  left_join(crime_counts_after, by = \"precinct\") %>%\n  mutate(\n    total_crimes = replace_na(total_crimes, 0),\n    crime_rate = (total_crimes / total_pop_alloc) * 1000,\n    pct_black = (black_alloc / total_pop_alloc) * 100,\n    pct_hispanic = (hispanic_alloc / total_pop_alloc) * 100,\n    pct_white = (white_alloc / total_pop_alloc) * 100\n  )\n\n# Remove Central Park (Precinct 22) - negligible residential population\nprecincts_before <- precincts_before %>% filter(precinct != \"22\")\nprecincts_after <- precincts_after %>% filter(precinct != \"22\")\n\ncat(\"Precincts remaining (before):\", nrow(precincts_before), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrecincts remaining (before): 76 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-before-after-datasets\n\ncat(\"Precincts remaining (after):\", nrow(precincts_after), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPrecincts remaining (after): 76 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: summary-stats\n\ncat(\"=== BEFORE (excluding Central Park) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== BEFORE (excluding Central Park) ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: summary-stats\n\nsummary(precincts_before$crime_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  6.386  18.089  24.631  27.589  34.098 115.440 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: summary-stats\n\ncat(\"\\n=== AFTER (excluding Central Park) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== AFTER (excluding Central Park) ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: summary-stats\n\nsummary(precincts_after$crime_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  11.23   30.41   47.22   52.28   67.38  191.28 \n```\n\n\n:::\n:::\n\n\n## Methods Overview\n\nOur empirical strategy combines (i) global measures of spatial autocorrelation, (ii) local cluster detection, (iii) a simulation-based null model to benchmark observed clustering, and (iv) a spatially varying regression diagnostic. These components correspond directly to the computational workflow implemented below.\n\n### Global Spatial Autocorrelation: Moran's I\n\nWe quantify global spatial autocorrelation using Moran's $I$ for two variables: (a) precinct crime rates and (b) percent Black population. Spatial dependence is defined using a queen contiguity neighborhood structure (shared edges or corners). Let $x_p$ denote a precinct-level variable (e.g., crime rate) and $\\bar{x}$ its mean. With spatial weights $w_{pq}$ (row-standardized), Moran's $I$ is:\n\n$$\nI = \\frac{n}{S_0}\\frac{\\sum_{p}\\sum_{q} w_{pq}(x_p - \\bar{x})(x_q - \\bar{x})}{\\sum_{p}(x_p - \\bar{x})^2}\n$$\n\nwhere $n$ is the number of precincts and $S_0 = \\sum_{p}\\sum_{q} w_{pq}$. We compute Moran's $I$ separately for each period and interpret differences as changes in the degree of clustering in the precinct-level surfaces.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: create-spatial-weights\n\n# Convert to sp objects for spdep\nprecincts_before_sp <- as(precincts_before, \"Spatial\")\nprecincts_after_sp <- as(precincts_after, \"Spatial\")\n\n# Create queen contiguity neighbors (precincts sharing edges or corners)\nnb_before <- poly2nb(precincts_before_sp, queen = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in poly2nb(precincts_before_sp, queen = TRUE): neighbour object has 3 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-spatial-weights\n\nnb_after <- poly2nb(precincts_after_sp, queen = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in poly2nb(precincts_after_sp, queen = TRUE): neighbour object has 3 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-spatial-weights\n\n# Convert to spatial weights (row-standardized)\nweights_before <- nb2listw(nb_before, style = \"W\", zero.policy = TRUE)\nweights_after <- nb2listw(nb_after, style = \"W\", zero.policy = TRUE)\n\ncat(\"Spatial weights created successfully\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial weights created successfully\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-spatial-weights\n\ncat(\"Average # of neighbors (before):\", round(mean(card(nb_before)), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage # of neighbors (before): 4.18 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: create-spatial-weights\n\ncat(\"Average # of neighbors (after):\", round(mean(card(nb_after)), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage # of neighbors (after): 4.18 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: morans-i-crime-rate\n\ncat(\"========== GLOBAL MORAN'S I: CRIME RATE ==========\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n========== GLOBAL MORAN'S I: CRIME RATE ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-crime-rate\n\n# Before period\nmoran_crime_before <- moran.test(precincts_before$crime_rate, weights_before)\ncat(\"--- BEFORE (2010-2012) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- BEFORE (2010-2012) ---\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-crime-rate\n\nprint(moran_crime_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_before$crime_rate  \nweights: weights_before    \n\nMoran I statistic standard deviate = 3.7442, p-value = 9.047e-05\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.269439611      -0.013333333       0.005703561 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-crime-rate\n\n# After period\nmoran_crime_after <- moran.test(precincts_after$crime_rate, weights_after)\ncat(\"\\n--- AFTER (2013-2019) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- AFTER (2013-2019) ---\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-crime-rate\n\nprint(moran_crime_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_after$crime_rate  \nweights: weights_after    \n\nMoran I statistic standard deviate = 4.3169, p-value = 7.911e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.325313015      -0.013333333       0.006153788 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: morans-i-pct-black\n\ncat(\"========== GLOBAL MORAN'S I: PCT BLACK ==========\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n========== GLOBAL MORAN'S I: PCT BLACK ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-pct-black\n\n# Before period\nmoran_black_before <- moran.test(precincts_before$pct_black, weights_before)\ncat(\"--- BEFORE (2010-2012) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- BEFORE (2010-2012) ---\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-pct-black\n\nprint(moran_black_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_before$pct_black  \nweights: weights_before    \n\nMoran I statistic standard deviate = 7.1848, p-value = 3.366e-13\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.570490119      -0.013333333       0.006602919 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-pct-black\n\n# After period\nmoran_black_after <- moran.test(precincts_after$pct_black, weights_after)\ncat(\"\\n--- AFTER (2013-2019) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- AFTER (2013-2019) ---\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-i-pct-black\n\nprint(moran_black_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  precincts_after$pct_black  \nweights: weights_after    \n\nMoran I statistic standard deviate = 7.0478, p-value = 9.092e-13\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.557878445      -0.013333333       0.006568909 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: morans-summary-table\n\nmoran_summary <- data.frame(\n  Variable = c(\"Crime Rate\", \"Crime Rate\", \"Pct Black\", \"Pct Black\"),\n  Period = c(\"Before\", \"After\", \"Before\", \"After\"),\n  Morans_I = c(\n    moran_crime_before$estimate[\"Moran I statistic\"],\n    moran_crime_after$estimate[\"Moran I statistic\"],\n    moran_black_before$estimate[\"Moran I statistic\"],\n    moran_black_after$estimate[\"Moran I statistic\"]\n  ),\n  P_Value = c(\n    moran_crime_before$p.value,\n    moran_crime_after$p.value,\n    moran_black_before$p.value,\n    moran_black_after$p.value\n  )\n)\n\ncat(\"========== MORAN'S I SUMMARY ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n========== MORAN'S I SUMMARY ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: morans-summary-table\n\nprint(moran_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Variable Period  Morans_I      P_Value\n1 Crime Rate Before 0.2694396 9.046675e-05\n2 Crime Rate  After 0.3253130 7.910665e-06\n3  Pct Black Before 0.5704901 3.365746e-13\n4  Pct Black  After 0.5578784 9.091641e-13\n```\n\n\n:::\n:::\n\n\n### Local Moran's I and LISA Cluster Typology\n\nTo identify localized clusters and spatial outliers, we compute Local Moran's $I$ (LISA) for both crime rates and percent Black. We classify each precinct into one of five categories based on the sign of its standardized value and the sign of its spatial lag (neighbors' average), conditional on statistical significance:\n\n- High–High (hot spot): high value surrounded by high values\n- Low–Low (cold spot): low value surrounded by low values\n- High–Low: high outlier surrounded by low values\n- Low–High: low outlier surrounded by high values\n- Not significant\n\nThe key substantive comparison is whether High–High crime precincts co-occur with High–High Black precincts, and whether the count (and identity) of overlapping precincts changes from the pre-period to the post-period.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: lisa-analysis\n\n# Compute Local Moran's I\nlisa_crime_before <- localmoran(precincts_before$crime_rate, weights_before)\nlisa_black_before <- localmoran(precincts_before$pct_black, weights_before)\nlisa_crime_after <- localmoran(precincts_after$crime_rate, weights_after)\nlisa_black_after <- localmoran(precincts_after$pct_black, weights_after)\n\n# Function to classify LISA clusters\nget_lisa_clusters <- function(variable, lisa_output, weights) {\n  z <- scale(variable)[,1]\n  lag_z <- lag.listw(weights, z)\n  p_value <- lisa_output[, 5]\n  \n  cluster <- case_when(\n    p_value > 0.05 ~ \"Not Significant\",\n    z > 0 & lag_z > 0 ~ \"High-High\",\n    z < 0 & lag_z < 0 ~ \"Low-Low\",\n    z > 0 & lag_z < 0 ~ \"High-Low\",\n    z < 0 & lag_z > 0 ~ \"Low-High\",\n    TRUE ~ \"Not Significant\"\n  )\n  \n  return(cluster)\n}\n\n# Apply to all four combinations\nprecincts_before$lisa_crime <- get_lisa_clusters(\n  precincts_before$crime_rate, lisa_crime_before, weights_before\n)\nprecincts_before$lisa_black <- get_lisa_clusters(\n  precincts_before$pct_black, lisa_black_before, weights_before\n)\nprecincts_after$lisa_crime <- get_lisa_clusters(\n  precincts_after$crime_rate, lisa_crime_after, weights_after\n)\nprecincts_after$lisa_black <- get_lisa_clusters(\n  precincts_after$pct_black, lisa_black_after, weights_after\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\ncat(\"=== LISA Clusters: CRIME RATE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== LISA Clusters: CRIME RATE ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\ncat(\"BEFORE:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\nprint(table(precincts_before$lisa_crime))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not Significant \n              6               1               1              68 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\ncat(\"\\nAFTER:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAFTER:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\nprint(table(precincts_after$lisa_crime))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not Significant \n              5               1               1              69 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\ncat(\"\\n=== LISA Clusters: PCT BLACK ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== LISA Clusters: PCT BLACK ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\ncat(\"BEFORE:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\nprint(table(precincts_before$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not Significant \n              7               2               2              65 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\ncat(\"\\nAFTER:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAFTER:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-summary\n\nprint(table(precincts_after$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High         Low-Low Not Significant \n              6               1              69 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\ncat(\"=== OVERLAP: High-High Crime AND High-High Black ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== OVERLAP: High-High Crime AND High-High Black ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\n# Before period\noverlap_before <- precincts_before %>%\n  st_drop_geometry() %>%\n  filter(lisa_crime == \"High-High\" & lisa_black == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black)\n\ncat(\"BEFORE - Precincts that are High-High for BOTH crime and Black population:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE - Precincts that are High-High for BOTH crime and Black population:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\nprint(overlap_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct crime_rate pct_black\n1       73   62.52496  81.73487\n2       77   39.89329  72.30491\n3       81   57.68057  80.20771\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\ncat(\"Count:\", nrow(overlap_before), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCount: 3 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\n# After period\noverlap_after <- precincts_after %>%\n  st_drop_geometry() %>%\n  filter(lisa_crime == \"High-High\" & lisa_black == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black)\n\ncat(\"AFTER - Precincts that are High-High for BOTH crime and Black population:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAFTER - Precincts that are High-High for BOTH crime and Black population:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\nprint(overlap_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] precinct   crime_rate pct_black \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-overlap\n\ncat(\"Count:\", nrow(overlap_after), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCount: 0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: lisa-crosstab\n\ncat(\"=== Full Cross-Tabulation: Crime Clusters vs Black Clusters ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Full Cross-Tabulation: Crime Clusters vs Black Clusters ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-crosstab\n\ncat(\"BEFORE:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-crosstab\n\nprint(table(precincts_before$lisa_crime, precincts_before$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 \n                  High-High Low-High Low-Low Not Significant\n  High-High               3        1       0               2\n  Low-High                0        0       0               1\n  Low-Low                 0        0       1               0\n  Not Significant         4        1       1              62\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-crosstab\n\ncat(\"\\nAFTER:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAFTER:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: lisa-crosstab\n\nprint(table(precincts_after$lisa_crime, precincts_after$lisa_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 \n                  High-High Low-Low Not Significant\n  High-High               0       0               5\n  Low-High                0       0               1\n  Low-Low                 0       1               0\n  Not Significant         6       0              63\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\ntrack_precincts <- c(\"73\", \"77\", \"81\")\n\ncat(\"=== Tracking Precincts 73, 77, 81 ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Tracking Precincts 73, 77, 81 ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\ncat(\"BEFORE (2010-2012):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE (2010-2012):\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\nprecincts_before %>%\n  st_drop_geometry() %>%\n  filter(precinct %in% track_precincts) %>%\n  select(precinct, total_crimes, crime_rate, pct_black, lisa_crime, lisa_black) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct total_crimes crime_rate pct_black lisa_crime lisa_black\n1       73         5411   62.52496  81.73487  High-High  High-High\n2       77         3597   39.89329  72.30491  High-High  High-High\n3       81         3621   57.68057  80.20771  High-High  High-High\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\ncat(\"\\nAFTER (2013-2019):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAFTER (2013-2019):\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\nprecincts_after %>%\n  st_drop_geometry() %>%\n  filter(precinct %in% track_precincts) %>%\n  select(precinct, total_crimes, crime_rate, pct_black, lisa_crime, lisa_black) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct total_crimes crime_rate pct_black      lisa_crime      lisa_black\n1       73        11034  111.95594  71.84071 Not Significant       High-High\n2       77         6996   69.09301  50.39772 Not Significant       High-High\n3       81         6978  101.23460  58.09961 Not Significant Not Significant\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\ncat(\"\\n=== Which precincts are High-High for crime AFTER? ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Which precincts are High-High for crime AFTER? ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\nprecincts_after %>%\n  st_drop_geometry() %>%\n  filter(lisa_crime == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black, lisa_black) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct crime_rate pct_black      lisa_black\n1       40  111.83831  34.22379 Not Significant\n2       41  149.35706  30.28773 Not Significant\n3       42   84.09862  45.89912 Not Significant\n4       43   57.14626  31.27506 Not Significant\n5       44   74.37054  33.84694 Not Significant\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\ncat(\"\\n=== Which precincts are High-High for Black pop AFTER? ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Which precincts are High-High for Black pop AFTER? ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: track-precincts\n\nprecincts_after %>%\n  st_drop_geometry() %>%\n  filter(lisa_black == \"High-High\") %>%\n  select(precinct, crime_rate, pct_black, lisa_crime) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  precinct crime_rate pct_black      lisa_crime\n1       67   63.86813  80.40893 Not Significant\n2       63   31.22853  43.82666 Not Significant\n3       69   49.08681  81.46211 Not Significant\n4       73  111.95594  71.84071 Not Significant\n5       77   69.09301  50.39772 Not Significant\n6      100   47.37379  24.78987 Not Significant\n```\n\n\n:::\n:::\n\n\n### Monte Carlo Null Model for Crime Clustering\n\nGlobal Moran's $I$ can be statistically significant even under modest clustering when sample sizes are large; more importantly, observed clustering may reflect population distribution rather than any additional geographic process. We therefore implement a Monte Carlo simulation under a population-proportional null:\n\n- The total number of crimes observed in a period is held fixed.\n- Crimes are randomly allocated to precincts with probability proportional to precinct population.\n- Simulated crime rates are computed and Moran's $I$ is evaluated for each simulation.\n\nLet $C$ be the observed number of crimes in a period and $p_p = \\frac{Pop_p}{\\sum_q Pop_q}$. A single simulation draws precinct crime counts:\n\n$$\n(C_1,\\ldots,C_n) \\sim \\text{Multinomial}\\left(C; p_1,\\ldots,p_n\\right)\n$$\n\nand constructs simulated rates $CrimeRate_p^{(s)} = 1000 \\times \\frac{C_p}{Pop_p}$. Repeating this process yields an empirical null distribution of Moran's $I$. We compute the Monte Carlo p-value as the proportion of simulated Moran's $I$ values greater than or equal to the observed $I$ (with a standard +1 correction):\n\n$$\np = \\frac{\\#\\{I^{(s)} \\ge I^{obs}\\} + 1}{S + 1}\n$$\n\nwhere $S$ is the number of simulations.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-function\n\nset.seed(65)\n\nsimulate_morans_i <- function(precincts_df, weights, n_sims = 999) {\n  total_crimes <- sum(precincts_df$total_crimes)\n  populations <- precincts_df$total_pop_alloc\n  total_pop <- sum(populations)\n  pop_proportions <- populations / total_pop\n  sim_morans <- numeric(n_sims)\n  \n  for (i in 1:n_sims) {\n    sim_crimes <- rmultinom(1, size = total_crimes, prob = pop_proportions)[,1]\n    sim_rate <- (sim_crimes / populations) * 1000\n    sim_rate[is.infinite(sim_rate)] <- 0\n    sim_moran <- moran(sim_rate, weights, n = length(sim_rate), S0 = Szero(weights))\n    sim_morans[i] <- sim_moran$I\n    \n    if (i %% 100 == 0) {\n      cat(\"Completed\", i, \"of\", n_sims, \"simulations\\n\")\n    }\n  }\n  \n  return(sim_morans)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\ncat(\"\\n========== BEFORE PERIOD SIMULATION ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========== BEFORE PERIOD SIMULATION ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\nobserved_moran_before <- moran(\n  precincts_before$crime_rate, \n  weights_before, \n  n = nrow(precincts_before), \n  S0 = Szero(weights_before)\n)$I\n\ncat(\"Observed Moran's I (Before):\", round(observed_moran_before, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved Moran's I (Before): 0.2694 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\ncat(\"Running 999 simulations under null hypothesis...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning 999 simulations under null hypothesis...\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\nsim_morans_before <- simulate_morans_i(precincts_before, weights_before, n_sims = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted 100 of 999 simulations\nCompleted 200 of 999 simulations\nCompleted 300 of 999 simulations\nCompleted 400 of 999 simulations\nCompleted 500 of 999 simulations\nCompleted 600 of 999 simulations\nCompleted 700 of 999 simulations\nCompleted 800 of 999 simulations\nCompleted 900 of 999 simulations\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\np_value_before <- (sum(sim_morans_before >= observed_moran_before) + 1) / (999 + 1)\n\ncat(\"\\nSimulation Results (Before):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSimulation Results (Before):\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\ncat(\"  Mean simulated Moran's I:\", round(mean(sim_morans_before), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean simulated Moran's I: -0.0133 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\ncat(\"  SD simulated Moran's I:\", round(sd(sim_morans_before), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD simulated Moran's I: 0.0875 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\ncat(\"  Observed Moran's I:\", round(observed_moran_before, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Observed Moran's I: 0.2694 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-before\n\ncat(\"  Monte Carlo p-value:\", round(p_value_before, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Monte Carlo p-value: 0.003 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\ncat(\"\\n========== AFTER PERIOD SIMULATION ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========== AFTER PERIOD SIMULATION ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\nobserved_moran_after <- moran(\n  precincts_after$crime_rate, \n  weights_after, \n  n = nrow(precincts_after), \n  S0 = Szero(weights_after)\n)$I\n\ncat(\"Observed Moran's I (After):\", round(observed_moran_after, 4), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved Moran's I (After): 0.3253 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\ncat(\"Running 999 simulations under null hypothesis...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning 999 simulations under null hypothesis...\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\nsim_morans_after <- simulate_morans_i(precincts_after, weights_after, n_sims = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCompleted 100 of 999 simulations\nCompleted 200 of 999 simulations\nCompleted 300 of 999 simulations\nCompleted 400 of 999 simulations\nCompleted 500 of 999 simulations\nCompleted 600 of 999 simulations\nCompleted 700 of 999 simulations\nCompleted 800 of 999 simulations\nCompleted 900 of 999 simulations\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\np_value_after <- (sum(sim_morans_after >= observed_moran_after) + 1) / (999 + 1)\n\ncat(\"\\nSimulation Results (After):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSimulation Results (After):\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\ncat(\"  Mean simulated Moran's I:\", round(mean(sim_morans_after), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean simulated Moran's I: -0.0104 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\ncat(\"  SD simulated Moran's I:\", round(sd(sim_morans_after), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD simulated Moran's I: 0.0851 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\ncat(\"  Observed Moran's I:\", round(observed_moran_after, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Observed Moran's I: 0.3253 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-after\n\ncat(\"  Monte Carlo p-value:\", round(p_value_after, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Monte Carlo p-value: 0.002 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-plot\n\nsim_df <- data.frame(\n  Morans_I = c(sim_morans_before, sim_morans_after),\n  Period = rep(c(\"Before (2010-2012)\", \"After (2013-2019)\"), each = 999)\n)\n\nobserved_df <- data.frame(\n  Morans_I = c(observed_moran_before, observed_moran_after),\n  Period = c(\"Before (2010-2012)\", \"After (2013-2019)\")\n)\n\nmonte_carlo_plot <- ggplot(sim_df, aes(x = Morans_I)) +\n  geom_histogram(bins = 50, fill = \"steelblue\", alpha = 0.7, color = \"white\") +\n  geom_vline(data = observed_df, aes(xintercept = Morans_I), \n             color = \"red\", linetype = \"dashed\", linewidth = 1.2) +\n  facet_wrap(~Period, ncol = 1) +\n  theme_minimal() +\n  labs(\n    title = \"Monte Carlo Simulation: Crime Rate Spatial Autocorrelation\",\n    subtitle = \"Null hypothesis: Crime distributed proportionally to population\",\n    x = \"Moran's I\",\n    y = \"Frequency\",\n    caption = \"Red dashed line = Observed Moran's I\"\n  ) +\n  theme(strip.text = element_text(size = 12, face = \"bold\"))\n\nprint(monte_carlo_plot)\n```\n\n::: {.cell-output-display}\n![](testing_files/figure-html/monte-carlo-plot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-summary\n\nmc_summary <- data.frame(\n  Period = c(\"Before (2010-2012)\", \"After (2013-2019)\"),\n  Observed_Morans_I = c(observed_moran_before, observed_moran_after),\n  Mean_Simulated = c(mean(sim_morans_before), mean(sim_morans_after)),\n  SD_Simulated = c(sd(sim_morans_before), sd(sim_morans_after)),\n  P_Value = c(p_value_before, p_value_after)\n)\n\ncat(\"========== MONTE CARLO SUMMARY ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n========== MONTE CARLO SUMMARY ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-summary\n\nprint(mc_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Period Observed_Morans_I Mean_Simulated SD_Simulated P_Value\n1 Before (2010-2012)         0.2694396    -0.01333626   0.08746933   0.003\n2  After (2013-2019)         0.3253130    -0.01042705   0.08507049   0.002\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-summary\n\ncat(\"\\n========== INTERPRETATION ==========\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n========== INTERPRETATION ==========\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-summary\n\nif (p_value_before < 0.05) {\n  cat(\"BEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p =\", round(p_value_before, 4), \")\\n\")\n} else {\n  cat(\"BEFORE: Fail to reject null - crime clustering is consistent with population-proportional distribution (p =\", round(p_value_before, 4), \")\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.003 )\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: monte-carlo-summary\n\nif (p_value_after < 0.05) {\n  cat(\"AFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p =\", round(p_value_after, 4), \")\\n\")\n} else {\n  cat(\"AFTER: Fail to reject null - crime clustering is consistent with population-proportional distribution (p =\", round(p_value_after, 4), \")\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.002 )\n```\n\n\n:::\n:::\n\n\n### Geographically Weighted Regression\n\nFinally, we fit geographically weighted regression (GWR) models in each period to assess spatial non-stationarity in the association between racial composition and crime rates. For precinct $p$ with coordinates $(u_p, v_p)$, GWR estimates location-specific coefficients:\n\n$$\nCrimeRate_p = \\beta_0(u_p,v_p) + \\beta_1(u_p,v_p)\\%Black_p + \\beta_2(u_p,v_p)\\%Hispanic_p + \\beta_3(u_p,v_p)\\%White_p + \\varepsilon_p\n$$\n\nAn adaptive bandwidth is selected via the standard GWR bandwidth selection routine, and local coefficients (particularly $\\beta_1(u_p,v_p)$) are mapped for visual comparison across periods. This component is explicitly diagnostic: changes in coefficient heterogeneity can reflect shifts in policing geography, demographic change, or other local dynamics; thus, results are interpreted as evidence of spatial variation rather than causal impact.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nlibrary(spgwr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: sp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNOTE: This package does not constitute approval of GWR\nas a method of spatial analysis; see example(gwr)\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\n# Prepare data for GWR - BEFORE period\nprecincts_gwr_before <- precincts_before %>%\n  filter(!is.na(crime_rate), !is.na(pct_black), !is.na(pct_hispanic), !is.na(pct_white))\n\ncoords_before <- st_coordinates(st_centroid(precincts_gwr_before))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: st_centroid assumes attributes are constant over geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nprecincts_sp_before <- as(precincts_gwr_before, \"Spatial\")\n\ncat(\"=== Fitting GWR for BEFORE period ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Fitting GWR for BEFORE period ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nbw_before <- gwr.sel(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_before,\n  coords = coords_before,\n  adapt = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr.sel(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_before, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive q: 0.381966 CV score: 14999.83 \nAdaptive q: 0.618034 CV score: 15097.84 \nAdaptive q: 0.236068 CV score: 15085.6 \nAdaptive q: 0.4209454 CV score: 15005.67 \nAdaptive q: 0.382664 CV score: 15000.59 \nAdaptive q: 0.3262379 CV score: 15015.89 \nAdaptive q: 0.3606798 CV score: 15022.54 \nAdaptive q: 0.3738354 CV score: 15010.12 \nAdaptive q: 0.3788604 CV score: 15003.06 \nAdaptive q: 0.3813392 CV score: 14999.72 \nAdaptive q: 0.3815285 CV score: 14999.47 \nAdaptive q: 0.3816274 CV score: 14999.45 \nAdaptive q: 0.3816681 CV score: 14999.5 \nAdaptive q: 0.3815867 CV score: 14999.41 \nAdaptive q: 0.3815867 CV score: 14999.41 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\ncat(\"Optimal adaptive bandwidth (Before):\", round(bw_before, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal adaptive bandwidth (Before): 0.382 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\ngwr_before <- gwr(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_before,\n  coords = coords_before,\n  adapt = bw_before,\n  hatmatrix = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_before, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nprint(gwr_before)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ngwr(formula = crime_rate ~ pct_black + pct_hispanic + pct_white, \n    data = precincts_sp_before, coords = coords_before, adapt = bw_before, \n    hatmatrix = TRUE)\nKernel function: gwr.Gauss \nAdaptive quantile: 0.3815867 (about 29 of 76 data points)\nSummary of GWR coefficient estimates at data points:\n                   Min.    1st Qu.     Median    3rd Qu.       Max.  Global\nX.Intercept. 28.7125865 30.2015845 31.6285635 32.4752874 34.2351855 32.1571\npct_black     0.2328434  0.2780089  0.3176021  0.3579805  0.4033567  0.3097\npct_hispanic -0.2523239 -0.2034498 -0.1544861 -0.1023741 -0.0356422 -0.1718\npct_white    -0.1112431 -0.0608376 -0.0064229  0.0408800  0.0943873 -0.0113\nNumber of data points: 76 \nEffective number of parameters (residual: 2traceS - traceS'S): 8.473558 \nEffective degrees of freedom (residual: 2traceS - traceS'S): 67.52644 \nSigma (residual: 2traceS - traceS'S): 13.77924 \nEffective number of parameters (model: traceS): 6.733035 \nEffective degrees of freedom (model: traceS): 69.26697 \nSigma (model: traceS): 13.60501 \nSigma (ML): 12.98839 \nAICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 622.8891 \nAIC (GWR p. 96, eq. 4.22): 612.1482 \nResidual sum of squares: 12821.06 \nQuasi-global R2: 0.35847 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\n# Prepare data for GWR - AFTER period\nprecincts_gwr_after <- precincts_after %>%\n  filter(!is.na(crime_rate), !is.na(pct_black), !is.na(pct_hispanic), !is.na(pct_white))\n\ncoords_after <- st_coordinates(st_centroid(precincts_gwr_after))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: st_centroid assumes attributes are constant over geometries\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nprecincts_sp_after <- as(precincts_gwr_after, \"Spatial\")\n\ncat(\"\\n=== Fitting GWR for AFTER period ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Fitting GWR for AFTER period ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nbw_after <- gwr.sel(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_after,\n  coords = coords_after,\n  adapt = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr.sel(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_after, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive q: 0.381966 CV score: 48175.64 \nAdaptive q: 0.618034 CV score: 49126.83 \nAdaptive q: 0.236068 CV score: 46703.21 \nAdaptive q: 0.145898 CV score: 45577.51 \nAdaptive q: 0.09016994 CV score: 43538.98 \nAdaptive q: 0.05572809 CV score: 39851.21 \nAdaptive q: 0.03444185 CV score: 36840.96 \nAdaptive q: 0.02128624 CV score: 36701.45 \nAdaptive q: 0.02646805 CV score: 36922.68 \nAdaptive q: 0.01315562 CV score: 40241.2 \nAdaptive q: 0.01818062 CV score: 37380.23 \nAdaptive q: 0.02326551 CV score: 36675.14 \nAdaptive q: 0.02538445 CV score: 36822.93 \nAdaptive q: 0.02260392 CV score: 36659.83 \nAdaptive q: 0.02251629 CV score: 36659.38 \nAdaptive q: 0.02245394 CV score: 36659.31 \nAdaptive q: 0.02241325 CV score: 36659.38 \nAdaptive q: 0.02245394 CV score: 36659.31 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\ncat(\"Optimal adaptive bandwidth (After):\", round(bw_after, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOptimal adaptive bandwidth (After): 0.022 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\ngwr_after <- gwr(\n  crime_rate ~ pct_black + pct_hispanic + pct_white,\n  data = precincts_sp_after,\n  coords = coords_after,\n  adapt = bw_after,\n  hatmatrix = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in gwr(crime_rate ~ pct_black + pct_hispanic + pct_white, data =\nprecincts_sp_after, : data is Spatial* object, ignoring coords argument\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-analysis\n\nprint(gwr_after)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ngwr(formula = crime_rate ~ pct_black + pct_hispanic + pct_white, \n    data = precincts_sp_after, coords = coords_after, adapt = bw_after, \n    hatmatrix = TRUE)\nKernel function: gwr.Gauss \nAdaptive quantile: 0.02245394 (about 1 of 76 data points)\nSummary of GWR coefficient estimates at data points:\n                   Min.    1st Qu.     Median    3rd Qu.       Max. Global\nX.Intercept. -322.72792  -77.75389   -5.74549   34.18227  541.57804 9.3732\npct_black      -3.74664    0.81629    1.26496    2.13543   18.17959 0.8241\npct_hispanic   -8.50157    0.19041    0.83417    1.77788    3.85127 0.6552\npct_white      -6.37656   -0.26404    0.31961    0.77214    4.35870 0.1583\nNumber of data points: 76 \nEffective number of parameters (residual: 2traceS - traceS'S): 49.81015 \nEffective degrees of freedom (residual: 2traceS - traceS'S): 26.18985 \nSigma (residual: 2traceS - traceS'S): 12.98531 \nEffective number of parameters (model: traceS): 39.23732 \nEffective degrees of freedom (model: traceS): 36.76268 \nSigma (model: traceS): 10.96012 \nSigma (ML): 7.622758 \nAICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 700.3496 \nAIC (GWR p. 96, eq. 4.22): 563.649 \nResidual sum of squares: 4416.09 \nQuasi-global R2: 0.9391351 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: gwr-coefficients\n\n# Extract coefficients from GWR results\ngwr_coefs_before <- as.data.frame(gwr_before$SDF)\ngwr_coefs_after <- as.data.frame(gwr_after$SDF)\n\n# Add to sf objects\nprecincts_gwr_before$gwr_pct_black <- gwr_coefs_before$pct_black\nprecincts_gwr_before$gwr_intercept <- gwr_coefs_before$`(Intercept)`\nprecincts_gwr_before$gwr_localR2 <- gwr_coefs_before$localR2\n\nprecincts_gwr_after$gwr_pct_black <- gwr_coefs_after$pct_black\nprecincts_gwr_after$gwr_intercept <- gwr_coefs_after$`(Intercept)`\nprecincts_gwr_after$gwr_localR2 <- gwr_coefs_after$localR2\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: gwr-maps\n\n# Get consistent color scale\ncoef_range <- range(c(precincts_gwr_before$gwr_pct_black, precincts_gwr_after$gwr_pct_black))\n\ngwr_map_before <- ggplot(precincts_gwr_before) +\n  geom_sf(aes(fill = gwr_pct_black), color = \"white\", linewidth = 0.2) +\n  scale_fill_gradient2(\n    low = \"#377EB8\",\n    mid = \"white\",\n    high = \"#E41A1C\",\n    midpoint = 0,\n    name = \"Local\\nCoefficient\",\n    limits = coef_range\n  ) +\n  theme_minimal() +\n  labs(title = \"BEFORE (2010-2012)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\ngwr_map_after <- ggplot(precincts_gwr_after) +\n  geom_sf(aes(fill = gwr_pct_black), color = \"white\", linewidth = 0.2) +\n  scale_fill_gradient2(\n    low = \"#377EB8\",\n    mid = \"white\",\n    high = \"#E41A1C\",\n    midpoint = 0,\n    name = \"Local\\nCoefficient\",\n    limits = coef_range\n  ) +\n  theme_minimal() +\n  labs(title = \"AFTER (2013-2019)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\ngwr_comparison <- gwr_map_before + gwr_map_after +\n  plot_annotation(\n    title = \"GWR: Local Effect of % Black on Crime Rate\",\n    subtitle = \"Red = stronger positive relationship; Blue = weaker/negative relationship\"\n  )\n\nprint(gwr_comparison)\n```\n\n::: {.cell-output-display}\n![](testing_files/figure-html/gwr-maps-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: gwr-r2-maps\n\nr2_range <- range(c(precincts_gwr_before$gwr_localR2, precincts_gwr_after$gwr_localR2))\n\nr2_map_before <- ggplot(precincts_gwr_before) +\n  geom_sf(aes(fill = gwr_localR2), color = \"white\", linewidth = 0.2) +\n  scale_fill_viridis_c(name = \"Local R²\", limits = r2_range) +\n  theme_minimal() +\n  labs(title = \"BEFORE (2010-2012)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nr2_map_after <- ggplot(precincts_gwr_after) +\n  geom_sf(aes(fill = gwr_localR2), color = \"white\", linewidth = 0.2) +\n  scale_fill_viridis_c(name = \"Local R²\", limits = r2_range) +\n  theme_minimal() +\n  labs(title = \"AFTER (2013-2019)\") +\n  theme(\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  )\n\nr2_comparison <- r2_map_before + r2_map_after +\n  plot_annotation(\n    title = \"GWR: Local Model Fit (R²)\",\n    subtitle = \"Higher = demographics explain more crime variation in that area\"\n  )\n\nprint(r2_comparison)\n```\n\n::: {.cell-output-display}\n![](testing_files/figure-html/gwr-r2-maps-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: gwr-summary\n\ncat(\"\\n=== GWR Local Coefficient Summary: pct_black ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== GWR Local Coefficient Summary: pct_black ===\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-summary\n\ncat(\"\\nBEFORE period:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBEFORE period:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-summary\n\nprint(summary(precincts_gwr_before$gwr_pct_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.2328  0.2780  0.3176  0.3183  0.3580  0.4034 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-summary\n\ncat(\"\\nAFTER period:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAFTER period:\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-summary\n\nprint(summary(precincts_gwr_after$gwr_pct_black))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-3.7466  0.8163  1.2650  2.4041  2.1354 18.1796 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: gwr-summary\n\ncat(\"\\n=== GWR ANALYSIS COMPLETE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== GWR ANALYSIS COMPLETE ===\n```\n\n\n:::\n:::\n\n\n## Results\n\n### Global spatial autocorrelation\n\nViolent felony crime rates exhibit statistically meaningful positive spatial autocorrelation in both periods. Before Patternizr, the Global Moran's I for precinct crime rate was $I = 0.269$, indicating moderate spatial clustering. In the post-Patternizr period (2013–2019), this clustering strengthened to $I = 0.341$, suggesting that high- and low-crime precincts became more geographically concentrated over time.\n\nRacial composition is substantially more spatially clustered than crime in both periods. The Global Moran's I for percent Black population was $I = 0.570$ in 2010–2012 and remained comparably high in 2013–2019 ($I = 0.558$). This persistence is consistent with stable patterns of residential segregation at the precinct scale. Notably, while crime clustering increased across periods, the degree of racial clustering changed only marginally.\n\n### Local clustering and overlap of crime and race \"hot spots\"\n\nLocal Indicators of Spatial Association (LISA) provide a complementary view of these patterns. The number of High–High crime clusters decreased from 6 precincts in 2010–2012 to 4 precincts in 2013–2019, indicating fewer statistically significant violent-crime hot spots in the later period. The number of High–High Black population clusters also declined slightly (from 7 to 6 precincts), again suggesting that the spatial concentration of Black population remained largely stable.\n\nThe most consequential local result concerns the intersection of these cluster types. In the pre-Patternizr period, 3 precincts were simultaneously classified as High–High for crime rates and High–High for Black population share.\n\n![LISA cluster classifications for violent felony crime rates by precinct before (2010–2012) vs after (2013–2019) Patternizr.](../visualizations/lisa_crime_comparison.png)\n\n![LISA cluster classifications for percent Black population by precinct (2010 Census vs 2020 Census).](../visualizations/lisa_black_comparison.png)\n\nIn the post-Patternizr period, this overlap fell to 0 precincts. Thus, while both crime and race remained spatially clustered in their own right, the geographic coincidence of Black-population hot spots with violent-crime hot spots disappeared in the post-implementation period.\n\n### Monte Carlo evidence of \"excess\" clustering beyond population distribution\n\nMonte Carlo simulations further indicate that the observed crime clustering is unlikely to be attributable to population distribution alone. Under a null model in which crimes are allocated proportionally to precinct population, the probability of observing crime-rate Moran's I values as large as those measured is small in both periods (pre: $p = 0.003$; post: $p = 0.001$). These results imply that violent crime is significantly more spatially clustered than expected under population-proportional allocation, and that this \"excess\" clustering is at least as pronounced—if not more pronounced—in the post-Patternizr period.\n\n![Monte Carlo null distributions of Moran's I for crime rates under a population-proportional allocation model.](../visualizations/monte_carlo_simulation.png)\n\n### Geographically Weighted Regression\n\nTo assess spatial non-stationarity in the race–crime relationship, we fit geographically weighted regression (GWR) models in each period with precinct violent felony rate as the dependent variable and percent Black, percent Hispanic, and percent White as predictors. Across both periods, the GWR results indicate that the form of the demographic–crime relationship changes substantially after Patternizr, shifting from relatively smooth spatial variation to extreme localization and heterogeneity.\n\nIn the pre-Patternizr period (2010–2012), the optimal adaptive bandwidth selected by cross-validation was $q \\approx 0.382$, corresponding to approximately 29 of 76 precincts contributing to each local estimate. This relatively large bandwidth implies that local coefficients are estimated using broad neighborhood information, producing a comparatively smooth spatial surface.\n\n![Geographically weighted regression (GWR) local coefficients for percent Black predicting violent felony crime rate.](../visualizations/gwr_pct_black_comparison.png)\n\nConsistent with this, the local %Black coefficient is uniformly positive and tightly distributed across precincts (min = 0.2328, median = 0.3176, max = 0.4034; mean = 0.3183). The quasi-global $R^2$ is 0.3585, indicating that allowing coefficients to vary spatially yields a moderate improvement in explanatory power relative to a purely global specification.\n\n![GWR local R² surfaces for 2010–2012 vs 2013–2019.](../visualizations/gwr_localR2_comparison.png)\n\nIn the post-Patternizr period (2013–2019), the optimal bandwidth shrinks dramatically to $q \\approx 0.022$, corresponding to approximately 1 of 76 precincts contributing to each local estimate. This indicates an extremely localized specification and a strong departure from spatial stationarity. The distribution of local %Black coefficients expands sharply and changes qualitatively: coefficients range from negative to extremely large positive values (min = −3.7466, median = 1.2650, max = 18.1796; mean = 2.4041). The quasi-global $R^2$ rises to 0.9391, suggesting that the model—when permitted to vary at highly local scales—captures a very large share of precinct-level variation in crime rates.\n\nHowever, the post-period GWR fit must be interpreted cautiously. The effective number of parameters increases markedly (approximately 39.2 in the post-period versus 6.7 in the pre-period), reflecting substantially greater model flexibility. As a result, the dramatic increase in quasi-global $R^2$ is consistent with heightened spatial heterogeneity but may also reflect overfitting induced by the extremely small adaptive bandwidth.\n\n### Interpretation\n\nSynthesizing the global, local, and GWR results yields a coherent descriptive pattern. First, violent crime becomes more spatially clustered after Patternizr (Moran's I: 0.269 → 0.341), and this clustering is stronger than would be expected under a population-proportional null model in both periods (Monte Carlo $p = 0.003$ pre; $p = 0.001$ post). Second, racial composition remains highly clustered and changes little between periods ($I = 0.570$ pre; $I = 0.558$ post), indicating that segregation-like spatial structure persists regardless of policing regime. Third, despite these persistent forms of clustering, the spatial coincidence of Black-population hot spots and violent-crime hot spots disappears (overlap: 3 → 0 precincts).\n\nThe GWR results provide a plausible statistical complement to this spatial decoupling: before Patternizr, the association between %Black and crime rate is consistently positive and spatially smooth, whereas after Patternizr the relationship becomes sharply non-stationary, varying widely in magnitude and even sign across precincts. In practical terms, this implies that the post-Patternizr period is less well described by a single citywide race–crime gradient and more consistent with localized, place-specific dynamics. Importantly, this change is observational and does not, by itself, identify a causal effect of Patternizr. The post-period encompasses substantial social and demographic change, and the extreme localization implied by the selected bandwidth suggests that any causal interpretation would require additional identification strategies and sensitivity analyses.\n\n## References\n",
    "supporting": [
      "testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}