<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Examinig claims of Racial Bias in Predictive Policing through a Geographic Perspective</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1acbab5e43ef2a5a12992dfc327cf6f1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Examinig claims of Racial Bias in Predictive Policing through a Geographic Perspective">
<meta name="citation_author" content="Fareeza Ali and Jackson Howes">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Literate programming;,citation_author=Donald E. Knuth;,citation_publication_date=1984-05;,citation_cover_date=1984-05;,citation_year=1984;,citation_fulltext_html_url=https://doi.org/10.1093/comjnl/27.2.97;,citation_issue=2;,citation_doi=10.1093/comjnl/27.2.97;,citation_issn=0010-4620;,citation_volume=27;,citation_journal_title=Comput. J.;,citation_publisher=Oxford University Press, Inc.;">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Examinig claims of Racial Bias in Predictive Policing through a Geographic Perspective</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Author</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Fareeza Ali and Jackson Howes </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Georgetown University
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#research-questions-and-hypotheses" id="toc-research-questions-and-hypotheses" class="nav-link" data-scroll-target="#research-questions-and-hypotheses">Research Questions and Hypotheses</a></li>
  <li><a href="#data-and-study-design" id="toc-data-and-study-design" class="nav-link" data-scroll-target="#data-and-study-design">Data and Study Design</a>
  <ul class="collapse">
  <li><a href="#spatial-units-and-coordinate-systems" id="toc-spatial-units-and-coordinate-systems" class="nav-link" data-scroll-target="#spatial-units-and-coordinate-systems">Spatial Units and Coordinate Systems</a></li>
  <li><a href="#demographic-data-census-blocks-to-precincts-via-areal-interpolation" id="toc-demographic-data-census-blocks-to-precincts-via-areal-interpolation" class="nav-link" data-scroll-target="#demographic-data-census-blocks-to-precincts-via-areal-interpolation">Demographic Data: Census Blocks to Precincts via Areal Interpolation</a></li>
  <li><a href="#crime-data-violent-felony-complaint-records" id="toc-crime-data-violent-felony-complaint-records" class="nav-link" data-scroll-target="#crime-data-violent-felony-complaint-records">Crime Data: Violent Felony Complaint Records</a></li>
  <li><a href="#prepost-comparison-windows" id="toc-prepost-comparison-windows" class="nav-link" data-scroll-target="#prepost-comparison-windows">Pre/Post Comparison Windows</a></li>
  </ul></li>
  <li><a href="#methods-overview" id="toc-methods-overview" class="nav-link" data-scroll-target="#methods-overview">Methods Overview</a>
  <ul class="collapse">
  <li><a href="#global-spatial-autocorrelation-morans-i" id="toc-global-spatial-autocorrelation-morans-i" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-morans-i">Global Spatial Autocorrelation: Moran’s (I)</a></li>
  <li><a href="#local-morans-i-and-lisa-cluster-typology" id="toc-local-morans-i-and-lisa-cluster-typology" class="nav-link" data-scroll-target="#local-morans-i-and-lisa-cluster-typology">Local Moran’s (I) and LISA Cluster Typology</a></li>
  <li><a href="#monte-carlo-null-model-for-crime-clustering" id="toc-monte-carlo-null-model-for-crime-clustering" class="nav-link" data-scroll-target="#monte-carlo-null-model-for-crime-clustering">Monte Carlo Null Model for Crime Clustering</a></li>
  <li><a href="#geographically-weighted-regression" id="toc-geographically-weighted-regression" class="nav-link" data-scroll-target="#geographically-weighted-regression">Geographically Weighted Regression</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#global-spatial-autocorrelation" id="toc-global-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-spatial-autocorrelation">Global spatial autocorrelation</a></li>
  <li><a href="#local-clustering-and-overlap-of-crime-and-race-hot-spots" id="toc-local-clustering-and-overlap-of-crime-and-race-hot-spots" class="nav-link" data-scroll-target="#local-clustering-and-overlap-of-crime-and-race-hot-spots">Local clustering and overlap of crime and race “hot spots”</a></li>
  <li><a href="#monte-carlo-evidence-of-excess-clustering-beyond-population-distribution" id="toc-monte-carlo-evidence-of-excess-clustering-beyond-population-distribution" class="nav-link" data-scroll-target="#monte-carlo-evidence-of-excess-clustering-beyond-population-distribution">Monte Carlo evidence of “excess” clustering beyond population distribution</a></li>
  <li><a href="#geographically-weighted-regression-1" id="toc-geographically-weighted-regression-1" class="nav-link" data-scroll-target="#geographically-weighted-regression-1">Geographically Weighted Regression</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="index-preview.html"><i class="bi bi-journal-code"></i>Article Notebook</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>Predictive policing systems have been repeatedly criticized for reproducing and amplifying racial disparities, yet empirical evaluation is complicated by the fact that “crime data” are not neutral measurements of underlying criminal behavior but administrative records produced through enforcement, reporting, and institutional decision-making. In this manuscript, we assess whether spatial patterns in recorded violent felony incidents changed in ways consistent with the claim that algorithmic policing intensified racially disparate enforcement. We adopt a geographic perspective, using NYPD precincts as the unit of analysis, violent felony complaint records as the outcome, and census-derived racial composition as the principal demographic covariate. Our design compares a pre-period (2010–2012) and a post-period (2013–2019) bracketing the implementation window of Patternizr, a predictive policing system introduced by the NYPD in 2013. We quantify global spatial autocorrelation in both crime rates and Black population share using Moran’s (I), identify local clusters using Local Indicators of Spatial Association (LISA), and assess whether observed clustering exceeds what would be expected under a population-proportional null model via Monte Carlo simulation. Finally, we use geographically weighted regression (GWR) to examine whether the relationship between racial composition and recorded crime rates became more spatially heterogeneous over time. We emphasize throughout that any observed differences are associational rather than causal, given concurrent neighborhood change and other confounds; nonetheless, this framework isolates concrete, testable spatial signatures that are directly relevant to claims of algorithmically mediated bias.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Public and scholarly debates over predictive policing have increasingly centered on a shared concern: that algorithmic systems trained on historically patterned enforcement data may re-entrench and intensify the very disparities they purport to mitigate. In the specific context of New York City, Patternizr has been described as a tool intended to assist in recognizing potentially related crime patterns; however, even systems framed as investigative aids may shape enforcement attention and thereby the geography of recorded crime. When police deploy resources unevenly across space, administrative “crime” data can reflect both underlying incidents and the spatial distribution of policing itself. As a result, testing claims of algorithmic bias requires methodological approaches that can separate (or at minimum, describe) changes in spatial concentration and demographic overlap.</p>
<p>We therefore pose a geographically grounded question: did the spatial structure of recorded violent felony crime become more clustered after the implementation of Patternizr, and did the geography of those clusters align differently with the geography of Black residential concentration? Importantly, our inferential target is not a direct causal estimate of Patternizr’s effect. Instead, we evaluate whether the <em>spatial signatures</em> of recorded crime—global clustering, local hot spots, and hot-spot overlap with racially concentrated precincts—changed in ways that are consistent with common critiques of predictive policing. We explicitly treat demographic change, including gentrification and population redistribution between 2010 and 2020, as a major confound that must be described alongside any policing-related interpretation.</p>
</section>
<section id="research-questions-and-hypotheses" class="level1">
<h1>Research Questions and Hypotheses</h1>
<p>Our analysis is organized around three primary research questions.</p>
<ol type="1">
<li><p><strong>Did the spatial clustering of violent felony <em>crime rates</em> change between the pre-Patternizr and post-Patternizr periods?</strong><br>
If predictive policing concentrated enforcement attention into a narrower set of precincts, we would expect increased spatial autocorrelation in recorded crime rates. This motivates comparison of global Moran’s (I) for precinct-level crime rates across periods.</p></li>
<li><p><strong>Did the spatial clustering of Black residential concentration change over the same window, and how does it relate to crime clustering?</strong><br>
Racial residential segregation produces strong spatial autocorrelation in demographic composition. If this structure is stable while crime clustering changes, then changes in the <em>relationship</em> between demographic clustering and crime clustering become substantively interpretable.</p></li>
<li><p><strong>Did the overlap between crime hot spots and Black population hot spots change?</strong><br>
We operationalize “hot spot” using LISA High–High clusters. A reduction in overlap may indicate either (i) a weakening association between racial concentration and recorded crime hot spots, or (ii) demographic change in the precincts that previously occupied both categories.</p></li>
</ol>
<p>In addition, we use geographically weighted regression (GWR) as a diagnostic to evaluate whether the local association between percent Black and precinct crime rates became more spatially heterogeneous over time. Substantively, a shift toward stronger spatial non-stationarity is consistent with a more localized policing geography, but this pattern can also arise from localized neighborhood change and other place-specific dynamics.</p>
</section>
<section id="data-and-study-design" class="level1">
<h1>Data and Study Design</h1>
<section id="spatial-units-and-coordinate-systems" class="level2">
<h2 class="anchored" data-anchor-id="spatial-units-and-coordinate-systems">Spatial Units and Coordinate Systems</h2>
<p>The unit of analysis is the NYPD precinct. We load an official precinct boundary shapefile and project it to an equal-area / planar coordinate system appropriate for spatial operations (EPSG:32118). All spatial overlays and neighborhood constructions (contiguity weights) are conducted in this projected CRS to ensure that area calculations and adjacency relationships are well-defined.</p>
<p>LOAD PRECINT SHAPEFILE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `nyc_precincts' from data source 
  `/home/jmchowes/Georgetown DSAN/Semester 1/DSAN 6750/Project/GIS_Final/data/data/nyc_precincts.geojson' 
  using driver `GeoJSON'
Simple feature collection with 77 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -74.25559 ymin: 40.49613 xmax: -73.70001 ymax: 40.91553
Geodetic CRS:  WGS 84</code></pre>
</div>
<a class="quarto-notebook-link" id="nblink-1" href="index-preview.html">Source: Article Notebook</a></div>
</section>
<section id="demographic-data-census-blocks-to-precincts-via-areal-interpolation" class="level2">
<h2 class="anchored" data-anchor-id="demographic-data-census-blocks-to-precincts-via-areal-interpolation">Demographic Data: Census Blocks to Precincts via Areal Interpolation</h2>
<p>Because precinct boundaries do not align with census block boundaries, we construct precinct-level demographics using areal interpolation. Specifically, we obtain census block geometries and block-level decennial census counts for 2010 and 2020. For each census year, we intersect census blocks with precinct polygons, compute the proportion of each block’s area contained within each precinct, and allocate block-level counts proportionally to those intersection weights. Summing the allocated counts across intersections yields precinct-level demographic totals.</p>
<p>DOWNLOAD 2020 BLOCK GEOMs</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tl_2020_36_tabblock20' from data source 
  `/home/jmchowes/Georgetown DSAN/Semester 1/DSAN 6750/Project/GIS_Final/data/data/tl_2020_36_tabblock20/tl_2020_36_tabblock20.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 288819 features and 17 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -79.76259 ymin: 40.47658 xmax: -71.77749 ymax: 45.01586
Geodetic CRS:  NAD83</code></pre>
</div>
</div>
<p>DOWNLOAD 2010 BLOCK GEOMs</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |                                                                      |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |===                                                                   |   5%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |=====                                                                 |   8%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |===========                                                           |  15%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |============                                                          |  16%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |==============                                                        |  21%
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |================                                                      |  23%
  |                                                                            
  |================                                                      |  24%
  |                                                                            
  |=================                                                     |  24%
  |                                                                            
  |=================                                                     |  25%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |===================                                                   |  28%
  |                                                                            
  |====================                                                  |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |=========================                                             |  36%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |=============================                                         |  41%
  |                                                                            
  |==============================                                        |  43%
  |                                                                            
  |================================                                      |  46%
  |                                                                            
  |==================================                                    |  48%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |======================================                                |  54%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |=========================================                             |  59%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |=============================================                         |  65%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |=====================================================                 |  76%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |===========================================================           |  84%
  |                                                                            
  |============================================================          |  86%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |======================================================================| 100%

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |================                                                      |  24%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=========================                                             |  35%
  |                                                                            
  |==============================                                        |  42%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |==================================                                    |  49%
  |                                                                            
  |===================================                                   |  51%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |=========================================                             |  59%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |===============================================                       |  68%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |==========================================================            |  83%
  |                                                                            
  |===========================================================           |  85%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |======================================================================| 100%

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |===========================                                           |  38%
  |                                                                            
  |==============================                                        |  42%
  |                                                                            
  |======================================                                |  54%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |======================================================================| 100%

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |=========                                                             |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |==============                                                        |  21%
  |                                                                            
  |=================                                                     |  25%
  |                                                                            
  |===================                                                   |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |===========================                                           |  38%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |===================================                                   |  49%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |=====================================                                 |  54%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |==============================================                        |  66%
  |                                                                            
  |===============================================                       |  67%
  |                                                                            
  |==================================================                    |  72%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |=====================================================                 |  75%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |==========================================================            |  82%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |=============================================================         |  88%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |===================================================================== |  99%
  |                                                                            
  |======================================================================| 100%

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |==========================                                            |  36%
  |                                                                            
  |==================================                                    |  48%
  |                                                                            
  |=====================================                                 |  53%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |==========================================================            |  82%
  |                                                                            
  |=============================================================         |  87%
  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |===================================================================== |  98%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
</div>
<p>Formally, let (b) index census blocks and (p) index precincts. Define the intersection area (A_{bp} = (b p)) and block area (A_b = (b)). The areal weight is</p>
<p><span class="math display">\[
w_{bp} = \frac{A_{bp}}{A_b}.
\]</span></p>
<p>For a block-level count (X_b) (e.g., total population, race counts), the precinct-allocated contribution from block (b) is</p>
<p><span class="math display">\[
X_{bp}^{\text{alloc}} = w_{bp} X_b,
\]</span></p>
<p>and the precinct-level total is</p>
<p><span class="math display">\[
X_p = \sum_{b} X_{bp}^{\text{alloc}}.
\]</span></p>
<p>We then compute precinct demographic shares (e.g., percent Black) as</p>
<p><span class="math display">\[
\%Black_p = 100 \times \frac{Black_p}{TotalPop_p},
\]</span></p>
<p>with analogous definitions for percent Hispanic and percent White.</p>
<p>This approach implicitly assumes uniform population density within each block. While imperfect, it is standard practice when translating census counts to non-nested administrative boundaries, and it produces internally consistent precinct-level denominators for per-capita crime rate computation.</p>
</section>
<section id="crime-data-violent-felony-complaint-records" class="level2">
<h2 class="anchored" data-anchor-id="crime-data-violent-felony-complaint-records">Crime Data: Violent Felony Complaint Records</h2>
<p>We load a cleaned violent felony complaint dataset containing point locations (latitude/longitude) and complaint dates. Complaint points are converted into an <code>sf</code> point object in WGS84 (EPSG:4326) and then filtered to a bounding box corresponding to New York City to remove obvious geocoding errors. Points are subsequently projected into EPSG:32118 for spatial joins and distance-consistent operations. Complaint dates are parsed to extract year, enabling period-based subsetting.</p>
<p>STANDARDIZE COL NAMES</p>
<p>LOAD AND PREP CRIME DATA</p>
</section>
<section id="prepost-comparison-windows" class="level2">
<h2 class="anchored" data-anchor-id="prepost-comparison-windows">Pre/Post Comparison Windows</h2>
<p>To reduce transitional ambiguity surrounding the implementation timeline, we define two non-overlapping windows:</p>
<ul>
<li><strong>Before</strong>: 2010–2012<br>
</li>
<li><strong>After</strong>: 2013–2019</li>
</ul>
<p>For each period, we spatially join complaint points to precinct polygons, count incidents per precinct, and compute the precinct-level violent felony rate per 1,000 residents:</p>
<p><span class="math display">\[
CrimeRate_p = 1000 \times \frac{Crimes_p}{TotalPop_p}.
\]</span></p>
<p>We exclude precinct 22 (Central Park) due to its negligible residential population, which otherwise induces artificially inflated per-capita rates and undermines interpretability.</p>
<p>BEFORE/AFTER DATASETS</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Crimes before (2010-2012): 201231"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Crimes after (2013-2019): 412321"</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precincts remaining (before): 76"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precincts remaining (after): 76"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== BEFORE (excluding Central Park) ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  6.386  18.089  24.631  27.589  34.098 115.440 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== AFTER (excluding Central Park) ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  11.23   30.41   47.22   52.28   67.38  191.28 </code></pre>
</div>
</div>
</section>
</section>
<section id="methods-overview" class="level1">
<h1>Methods Overview</h1>
<p>Our empirical strategy combines (i) global measures of spatial autocorrelation, (ii) local cluster detection, (iii) a simulation-based null model to benchmark observed clustering, and (iv) a spatially varying regression diagnostic. These components correspond directly to the computational workflow implemented below.</p>
<section id="global-spatial-autocorrelation-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="global-spatial-autocorrelation-morans-i">Global Spatial Autocorrelation: Moran’s (I)</h2>
<p>We quantify global spatial autocorrelation using Moran’s (I) for two variables: (a) precinct crime rates and (b) percent Black population. Spatial dependence is defined using a queen contiguity neighborhood structure (shared edges or corners). Let (x_p) denote a precinct-level variable (e.g., crime rate) and ({x}) its mean. With spatial weights (w_{pq}) (row-standardized), Moran’s (I) is</p>
<p><span class="math display">\[
I = \frac{n}{S_0}\frac{\sum_{p}\sum_{q} w_{pq}(x_p - \bar{x})(x_q - \bar{x})}{\sum_{p}(x_p - \bar{x})^2},
\]</span></p>
<p>where (n) is the number of precincts and (S_0 = <em>{p}</em>{q} w_{pq}). We compute Moran’s (I) separately for each period and interpret differences as changes in the degree of clustering in the precinct-level surfaces.</p>
<p>VERIFY DATA &amp; check for outliers</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== BEFORE PERIOD (2010-2012 crimes + 2010 census) ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "N precincts: 76"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  6.386  18.089  24.631  27.589  34.098 115.440 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.041   5.261  16.000  26.677  41.335  91.542 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== AFTER PERIOD (2013-2019 crimes + 2020 census) ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "N precincts: 76"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  11.23   30.41   47.22   52.28   67.38  191.28 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.091   5.030  13.922  22.969  33.941  81.462 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Top 5 crime rates - BEFORE ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  precinct total_crimes total_pop_alloc crime_rate
1       14         2378        20599.48  115.43978
2       41         3339        52157.85   64.01721
3       73         5411        86541.43   62.52496
4       81         3621        62776.77   57.68057
5       25         2440        47368.53   51.51099</code></pre>
</div>
</div>
<p>SPATIAL WEIGHTS AND MORANS I CREATE SPATIAL WEIGHTS MATRIX</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Spatial weights created successfully"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Average # of neighbors (before): 4.18"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Average # of neighbors (after): 4.18"</code></pre>
</div>
</div>
<p>GLOBAL MORANS I FOR CRIME RATE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "========== GLOBAL MORAN'S I: CRIME RATE =========="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- BEFORE (2010-2012) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  precincts_before$crime_rate  
weights: weights_before    

Moran I statistic standard deviate = 3.7442, p-value = 9.047e-05
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.269439611      -0.013333333       0.005703561 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- AFTER (2013-2019) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  precincts_after$crime_rate  
weights: weights_after    

Moran I statistic standard deviate = 4.3169, p-value = 7.911e-06
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.325313015      -0.013333333       0.006153788 </code></pre>
</div>
</div>
<p>GOBAL MORANS I FOR PERCENT OF BLACK POP</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "========== GLOBAL MORAN'S I: PCT BLACK =========="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- BEFORE (2010-2012) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  precincts_before$pct_black  
weights: weights_before    

Moran I statistic standard deviate = 7.1848, p-value = 3.366e-13
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.570490119      -0.013333333       0.006602919 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- AFTER (2013-2019) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  precincts_after$pct_black  
weights: weights_after    

Moran I statistic standard deviate = 7.0478, p-value = 9.092e-13
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.557878445      -0.013333333       0.006568909 </code></pre>
</div>
</div>
<p>SUMMARY TABLE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "========== MORAN'S I SUMMARY =========="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    Variable Period  Morans_I      P_Value
1 Crime Rate Before 0.2694396 9.046675e-05
2 Crime Rate  After 0.3253130 7.910665e-06
3  Pct Black Before 0.5704901 3.365746e-13
4  Pct Black  After 0.5578784 9.091641e-13</code></pre>
</div>
</div>
</section>
<section id="local-morans-i-and-lisa-cluster-typology" class="level2">
<h2 class="anchored" data-anchor-id="local-morans-i-and-lisa-cluster-typology">Local Moran’s (I) and LISA Cluster Typology</h2>
<p>To identify localized clusters and spatial outliers, we compute Local Moran’s (I) (LISA) for both crime rates and percent Black. We classify each precinct into one of five categories based on the sign of its standardized value and the sign of its spatial lag (neighbors’ average), conditional on statistical significance:</p>
<ul>
<li>High–High (hot spot): high value surrounded by high values<br>
</li>
<li>Low–Low (cold spot): low value surrounded by low values<br>
</li>
<li>High–Low: high outlier surrounded by low values<br>
</li>
<li>Low–High: low outlier surrounded by high values<br>
</li>
<li>Not significant</li>
</ul>
<p>The key substantive comparison is whether High–High crime precincts co-occur with High–High Black precincts, and whether the count (and identity) of overlapping precincts changes from the pre-period to the post-period.</p>
<p>LOCAL MORANS I (LISA)</p>
<p>CREATE LISA CLUSTER CATS</p>
<p>SUMMARY TABLE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== LISA Clusters: CRIME RATE ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BEFORE:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
      High-High        Low-High         Low-Low Not Significant 
              6               1               1              68 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AFTER:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
      High-High        Low-High         Low-Low Not Significant 
              5               1               1              69 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== LISA Clusters: PCT BLACK ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BEFORE:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
      High-High        Low-High         Low-Low Not Significant 
              7               2               2              65 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AFTER:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
      High-High         Low-Low Not Significant 
              6               1              69 </code></pre>
</div>
</div>
<p>KEY QUESTION - OVERLAP</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== OVERLAP: High-High Crime AND High-High Black ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BEFORE - Precincts that are High-High for BOTH crime and Black population:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  precinct crime_rate pct_black
1       73   62.52496  81.73487
2       77   39.89329  72.30491
3       81   57.68057  80.20771</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Count: 3"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AFTER - Precincts that are High-High for BOTH crime and Black population:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] precinct   crime_rate pct_black 
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Count: 0"</code></pre>
</div>
</div>
<p>CROSS TABULATION</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Full Cross-Tabulation: Crime Clusters vs Black Clusters ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BEFORE:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 
                  High-High Low-High Low-Low Not Significant
  High-High               3        1       0               2
  Low-High                0        0       0               1
  Low-Low                 0        0       1               0
  Not Significant         4        1       1              62</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AFTER:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                 
                  High-High Low-Low Not Significant
  High-High               0       0               5
  Low-High                0       0               1
  Low-Low                 0       1               0
  Not Significant         6       0              63</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Tracking Precincts 73, 77, 81 ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "BEFORE (2010-2012):"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  precinct total_crimes crime_rate pct_black lisa_crime lisa_black
1       73         5411   62.52496  81.73487  High-High  High-High
2       77         3597   39.89329  72.30491  High-High  High-High
3       81         3621   57.68057  80.20771  High-High  High-High</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AFTER (2013-2019):"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  precinct total_crimes crime_rate pct_black      lisa_crime      lisa_black
1       73        11034  111.95594  71.84071 Not Significant       High-High
2       77         6996   69.09301  50.39772 Not Significant       High-High
3       81         6978  101.23460  58.09961 Not Significant Not Significant</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Which precincts are High-High for crime AFTER? ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  precinct crime_rate pct_black      lisa_black
1       40  111.83831  34.22379 Not Significant
2       41  149.35706  30.28773 Not Significant
3       42   84.09862  45.89912 Not Significant
4       43   57.14626  31.27506 Not Significant
5       44   74.37054  33.84694 Not Significant</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Which precincts are High-High for Black pop AFTER? ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  precinct crime_rate pct_black      lisa_crime
1       67   63.86813  80.40893 Not Significant
2       63   31.22853  43.82666 Not Significant
3       69   49.08681  81.46211 Not Significant
4       73  111.95594  71.84071 Not Significant
5       77   69.09301  50.39772 Not Significant
6      100   47.37379  24.78987 Not Significant</code></pre>
</div>
</div>
<p>“=== Tracking Precincts 73, 77, 81 ===” [1] “BEFORE (2010-2012):” precinct total_crimes crime_rate pct_black lisa_crime lisa_black 1 73 5411 62.52496 81.73487 High-High High-High 2 77 3597 39.89329 72.30491 High-High High-High 3 81 3621 57.68057 80.20771 High-High High-High [1] “AFTER (2013-2019):” precinct total_crimes crime_rate pct_black lisa_crime lisa_black 1 73 4254 43.16300 71.84071 Not Significant High-High 2 77 2467 24.36427 50.39772 Not Significant High-High 3 81 2601 37.73448 58.09961 Not Significant Not Significant [1] “=== Which precincts are High-High for crime AFTER? ===” precinct crime_rate pct_black lisa_black 1 40 49.56718 34.22379 Not Significant 2 41 50.61239 30.28773 Not Significant 3 42 36.31798 45.89912 Not Significant 4 44 29.94631 33.84694 Not Significant [1] “=== Which precincts are High-High for Black pop AFTER? ===” precinct crime_rate pct_black lisa_crime 1 67 24.55377 80.40893 Not Significant 2 63 11.55723 43.82666 Not Significant 3 69 17.14669 81.46211 Not Significant 4 73 43.16300 71.84071 Not Significant 5 77 24.36427 50.39772 Not Significant 6 100 19.17792 24.78987 Not Significant</p>
<p>LISA MAPS</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-20-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-20-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="index_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-20-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="index_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-20-4.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="index_files/figure-html/unnamed-chunk-20-4.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-20-5.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="index_files/figure-html/unnamed-chunk-20-5.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-20-6.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="index_files/figure-html/unnamed-chunk-20-6.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maps saved!"</code></pre>
</div>
</div>
</section>
<section id="monte-carlo-null-model-for-crime-clustering" class="level2">
<h2 class="anchored" data-anchor-id="monte-carlo-null-model-for-crime-clustering">Monte Carlo Null Model for Crime Clustering</h2>
<p>Global Moran’s (I) can be statistically significant even under modest clustering when sample sizes are large; more importantly, observed clustering may reflect population distribution rather than any additional geographic process. We therefore implement a Monte Carlo simulation under a population-proportional null:</p>
<ul>
<li>The total number of crimes observed in a period is held fixed.</li>
<li>Crimes are randomly allocated to precincts with probability proportional to precinct population.</li>
<li>Simulated crime rates are computed and Moran’s (I) is evaluated for each simulation.</li>
</ul>
<p>Let (C) be the observed number of crimes in a period and (p_p = ). A single simulation draws precinct crime counts</p>
<p><span class="math display">\[
(C_1,\ldots,C_n) \sim \text{Multinomial}\left(C; p_1,\ldots,p_n\right),
\]</span></p>
<p>and constructs simulated rates (CrimeRate_p^{(s)} = 1000 ). Repeating this process yields an empirical null distribution of Moran’s (I). We compute the Monte Carlo p-value as the proportion of simulated Moran’s (I) values greater than or equal to the observed (I) (with a standard +1 correction):</p>
<p><span class="math display">\[
p = \frac{\#\{I^{(s)} \ge I^{obs}\} + 1}{S + 1},
\]</span></p>
<p>where (S) is the number of simulations.</p>
<p>MONTE CARLO SIMULATION</p>
<p>RUN SIMS FOR BEFORE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
========== BEFORE PERIOD SIMULATION ==========</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed Moran's I (Before): 0.2694 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Running 999 simulations under null hypothesis...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Completed 100 of 999 simulations
Completed 200 of 999 simulations
Completed 300 of 999 simulations
Completed 400 of 999 simulations
Completed 500 of 999 simulations
Completed 600 of 999 simulations
Completed 700 of 999 simulations
Completed 800 of 999 simulations
Completed 900 of 999 simulations</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Simulation Results (Before):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean simulated Moran's I: -0.0133 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD simulated Moran's I: 0.0875 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Observed Moran's I: 0.2694 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Monte Carlo p-value: 0.003 </code></pre>
</div>
</div>
<p>RUN SIMS FOR AFTER</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
========== AFTER PERIOD SIMULATION ==========</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed Moran's I (After): 0.3253 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Running 999 simulations under null hypothesis...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Completed 100 of 999 simulations
Completed 200 of 999 simulations
Completed 300 of 999 simulations
Completed 400 of 999 simulations
Completed 500 of 999 simulations
Completed 600 of 999 simulations
Completed 700 of 999 simulations
Completed 800 of 999 simulations
Completed 900 of 999 simulations</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Simulation Results (After):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean simulated Moran's I: -0.0104 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD simulated Moran's I: 0.0851 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Observed Moran's I: 0.3253 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Monte Carlo p-value: 0.002 </code></pre>
</div>
</div>
<p>visualize histogram of sims</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-24-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>SUMMARY TABLE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "========== MONTE CARLO SUMMARY =========="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              Period Observed_Morans_I Mean_Simulated SD_Simulated P_Value
1 Before (2010-2012)         0.2694396    -0.01333626   0.08746933   0.003
2  After (2013-2019)         0.3253130    -0.01042705   0.08507049   0.002</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
========== INTERPRETATION ==========</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>BEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.003 )</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>AFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.002 )</code></pre>
</div>
</div>
<p>The blue histograms show what Moran’s I values look like under the null hypothesis (crime distributed proportionally to population). They’re centered around 0 (no spatial autocorrelation).The red dashed line is observed Moran’s I - way out in the right tail for both periods.</p>
<p>In both periods, crime is significantly MORE clustered than we would expect if it were simply distributed proportionally to population. - If crime happened randomly based on where people live, we’d expect Moran’s I ≈ 0 - But we observe Moran’s I of 0.27-0.33, which is far outside what we’d expect by chance - This means there’s “excess” spatial clustering of crime beyond what population explains</p>
<p>[1] “========== MONTE CARLO SUMMARY ==========” &gt; print(mc_summary) Period Observed_Morans_I Mean_Simulated SD_Simulated P_Value 1 Before (2010-2012) 0.2694396 -0.01333626 0.08746933 0.003 2 After (2013-2019) 0.3253130 -0.01042705 0.08507049 0.002</p>
<p>========== INTERPRETATION ========== BEFORE: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.003 ) AFTER: Reject null hypothesis - crime is MORE clustered than expected under population-proportional distribution (p = 0.002 )</p>
</section>
<section id="geographically-weighted-regression" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-regression">Geographically Weighted Regression</h2>
<p>Finally, we fit geographically weighted regression (GWR) models in each period to assess spatial non-stationarity in the association between racial composition and crime rates. For precinct (p) with coordinates ((u_p, v_p)), GWR estimates location-specific coefficients:</p>
<p><span class="math display">\[
CrimeRate_p = \beta_0(u_p,v_p) + \beta_1(u_p,v_p)\%Black_p + \beta_2(u_p,v_p)\%Hispanic_p + \beta_3(u_p,v_p)\%White_p + \varepsilon_p.
\]</span></p>
<p>An adaptive bandwidth is selected via the standard GWR bandwidth selection routine, and local coefficients (particularly (_1(u_p,v_p))) are mapped for visual comparison across periods. This component is explicitly diagnostic: changes in coefficient heterogeneity can reflect shifts in policing geography, demographic change, or other local dynamics; thus, results are interpreted as evidence of spatial variation rather than causal impact.</p>
<p>GEOGRAPHICALLY WEIGHT REGRESSION</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Fitting GWR for BEFORE period ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive q: 0.381966 CV score: 14999.83 
Adaptive q: 0.618034 CV score: 15097.84 
Adaptive q: 0.236068 CV score: 15085.6 
Adaptive q: 0.4209454 CV score: 15005.67 
Adaptive q: 0.382664 CV score: 15000.59 
Adaptive q: 0.3262379 CV score: 15015.89 
Adaptive q: 0.3606798 CV score: 15022.54 
Adaptive q: 0.3738354 CV score: 15010.12 
Adaptive q: 0.3788604 CV score: 15003.06 
Adaptive q: 0.3813392 CV score: 14999.72 
Adaptive q: 0.3815285 CV score: 14999.47 
Adaptive q: 0.3816274 CV score: 14999.45 
Adaptive q: 0.3816681 CV score: 14999.5 
Adaptive q: 0.3815867 CV score: 14999.41 
Adaptive q: 0.3815867 CV score: 14999.41 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimal adaptive bandwidth (Before): 0.382 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
gwr(formula = crime_rate ~ pct_black + pct_hispanic + pct_white, 
    data = precincts_sp_before, coords = coords_before, adapt = bw_before, 
    hatmatrix = TRUE)
Kernel function: gwr.Gauss 
Adaptive quantile: 0.3815867 (about 29 of 76 data points)
Summary of GWR coefficient estimates at data points:
                   Min.    1st Qu.     Median    3rd Qu.       Max.  Global
X.Intercept. 28.7125865 30.2015845 31.6285635 32.4752874 34.2351855 32.1571
pct_black     0.2328434  0.2780089  0.3176021  0.3579805  0.4033567  0.3097
pct_hispanic -0.2523239 -0.2034498 -0.1544861 -0.1023741 -0.0356422 -0.1718
pct_white    -0.1112431 -0.0608376 -0.0064229  0.0408800  0.0943873 -0.0113
Number of data points: 76 
Effective number of parameters (residual: 2traceS - traceS'S): 8.473558 
Effective degrees of freedom (residual: 2traceS - traceS'S): 67.52644 
Sigma (residual: 2traceS - traceS'S): 13.77924 
Effective number of parameters (model: traceS): 6.733035 
Effective degrees of freedom (model: traceS): 69.26697 
Sigma (model: traceS): 13.60501 
Sigma (ML): 12.98839 
AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 622.8891 
AIC (GWR p. 96, eq. 4.22): 612.1482 
Residual sum of squares: 12821.06 
Quasi-global R2: 0.35847 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== Fitting GWR for AFTER period ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive q: 0.381966 CV score: 48175.64 
Adaptive q: 0.618034 CV score: 49126.83 
Adaptive q: 0.236068 CV score: 46703.21 
Adaptive q: 0.145898 CV score: 45577.51 
Adaptive q: 0.09016994 CV score: 43538.98 
Adaptive q: 0.05572809 CV score: 39851.21 
Adaptive q: 0.03444185 CV score: 36840.96 
Adaptive q: 0.02128624 CV score: 36701.45 
Adaptive q: 0.02646805 CV score: 36922.68 
Adaptive q: 0.01315562 CV score: 40241.2 
Adaptive q: 0.01818062 CV score: 37380.23 
Adaptive q: 0.02326551 CV score: 36675.14 
Adaptive q: 0.02538445 CV score: 36822.93 
Adaptive q: 0.02260392 CV score: 36659.83 
Adaptive q: 0.02251629 CV score: 36659.38 
Adaptive q: 0.02245394 CV score: 36659.31 
Adaptive q: 0.02241325 CV score: 36659.38 
Adaptive q: 0.02245394 CV score: 36659.31 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimal adaptive bandwidth (After): 0.022 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
gwr(formula = crime_rate ~ pct_black + pct_hispanic + pct_white, 
    data = precincts_sp_after, coords = coords_after, adapt = bw_after, 
    hatmatrix = TRUE)
Kernel function: gwr.Gauss 
Adaptive quantile: 0.02245394 (about 1 of 76 data points)
Summary of GWR coefficient estimates at data points:
                   Min.    1st Qu.     Median    3rd Qu.       Max. Global
X.Intercept. -322.72792  -77.75389   -5.74549   34.18227  541.57804 9.3732
pct_black      -3.74664    0.81629    1.26496    2.13543   18.17959 0.8241
pct_hispanic   -8.50157    0.19041    0.83417    1.77788    3.85127 0.6552
pct_white      -6.37656   -0.26404    0.31961    0.77214    4.35870 0.1583
Number of data points: 76 
Effective number of parameters (residual: 2traceS - traceS'S): 49.81015 
Effective degrees of freedom (residual: 2traceS - traceS'S): 26.18985 
Sigma (residual: 2traceS - traceS'S): 12.98531 
Effective number of parameters (model: traceS): 39.23732 
Effective degrees of freedom (model: traceS): 36.76268 
Sigma (model: traceS): 10.96012 
Sigma (ML): 7.622758 
AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 700.3496 
AIC (GWR p. 96, eq. 4.22): 563.649 
Residual sum of squares: 4416.09 
Quasi-global R2: 0.9391351 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-26-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== GWR Local Coefficient Summary: pct_black ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
BEFORE period:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2328  0.2780  0.3176  0.3183  0.3580  0.4034 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
AFTER period:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-3.7466  0.8163  1.2650  2.4041  2.1354 18.1796 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-26-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="index_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== GWR ANALYSIS COMPLETE ===</code></pre>
</div>
</div>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="global-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="global-spatial-autocorrelation">Global spatial autocorrelation</h2>
<p>Violent felony crime rates exhibit statistically meaningful positive spatial autocorrelation in both periods. Before Patternizr, the Global Moran’s I for precinct crime rate was 𝐼 = 0.269, indicating moderate spatial clustering. In the post-Patternizr period (2013–2019), this clustering strengthened to 𝐼 = 0.341, suggesting that high- and low-crime precincts became more geographically concentrated over time.</p>
<p>Racial composition is substantially more spatially clustered than crime in both periods. The Global Moran’s I for percent Black population was <span class="math inline">\(𝐼 = 0.570\)</span> in 2010–2012 and remained comparably high in 2013–2019 (<span class="math inline">\(𝐼 = 0.558\)</span>). This persistence is consistent with stable patterns of residential segregation at the precinct scale. Notably, while crime clustering increased across periods, the degree of racial clustering changed only marginally.</p>
</section>
<section id="local-clustering-and-overlap-of-crime-and-race-hot-spots" class="level2">
<h2 class="anchored" data-anchor-id="local-clustering-and-overlap-of-crime-and-race-hot-spots">Local clustering and overlap of crime and race “hot spots”</h2>
<p>Local Indicators of Spatial Association (LISA) provide a complementary view of these patterns. The number of High–High crime clusters decreased from 6 precincts in 2010–2012 to 4 precincts in 2013–2019, indicating fewer statistically significant violent-crime hot spots in the later period. The number of High–High Black population clusters also declined slightly (from 7 to 6 precincts), again suggesting that the spatial concentration of Black population remained largely stable.</p>
<p>The most consequential local result concerns the intersection of these cluster types. In the pre-Patternizr period, 3 precincts were simultaneously classified as High–High for crime rates and High–High for Black population share.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="lisa_crime_comparison.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="lisa_crime_comparison.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-cap="LISA cluster classifications for violent felony crime rates by precinct before (2010–2012) vs after (2013–2019) Patternizr. High–High clusters indicate local crime hot spots." alt="Side-by-side LISA cluster maps for crime rates, before vs after."></a></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="lisa_black_comparison.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="lisa_black_comparison.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-cap="LISA cluster classifications for percent Black population by precinct (2010 Census vs 2020 Census). High–High clusters indicate areas of concentrated Black residential presence." alt="Side-by-side LISA cluster maps for percent Black population, 2010 vs 2020."></a></p>
</figure>
</div>
<p>In the post-Patternizr period, this overlap fell to 0 precincts. Thus, while both crime and race remained spatially clustered in their own right, the geographic coincidence of Black-population hot spots with violent-crime hot spots disappeared in the post-implementation period.</p>
</section>
<section id="monte-carlo-evidence-of-excess-clustering-beyond-population-distribution" class="level2">
<h2 class="anchored" data-anchor-id="monte-carlo-evidence-of-excess-clustering-beyond-population-distribution">Monte Carlo evidence of “excess” clustering beyond population distribution</h2>
<p>Monte Carlo simulations further indicate that the observed crime clustering is unlikely to be attributable to population distribution alone. Under a null model in which crimes are allocated proportionally to precinct population, the probability of observing crime-rate Moran’s I values as large as those measured is small in both periods (pre: <span class="math inline">\(𝑝 = 0.003\)</span>; post: <span class="math inline">\(𝑝 =0.001\)</span>). These results imply that violent crime is significantly more spatially clustered than expected under population-proportional allocation, and that this “excess” clustering is at least as pronounced—if not more pronounced—in the post-Patternizr period.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="monte_carlo_simulation.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="monte_carlo_simulation.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-cap="Monte Carlo null distributions of Moran’s I for crime rates under a population-proportional allocation model. The red dashed line marks the observed Moran’s I for each period." alt="Faceted histograms of simulated Moran’s I values for before vs after, with observed marked."></a></p>
</figure>
</div>
</section>
<section id="geographically-weighted-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-regression-1">Geographically Weighted Regression</h2>
<p>To assess spatial non-stationarity in the race–crime relationship, we fit geographically weighted regression (GWR) models in each period with precinct violent felony rate as the dependent variable and percent Black, percent Hispanic, and percent White as predictors. Across both periods, the GWR results indicate that the form of the demographic–crime relationship changes substantially after Patternizr, shifting from relatively smooth spatial variation to extreme localization and heterogeneity.</p>
<p>In the pre-Patternizr period (2010–2012), the optimal adaptive bandwidth selected by cross-validation was <span class="math inline">\(q≈0.382\)</span>, corresponding to approximately 29 of 76 precincts contributing to each local estimate. This relatively large bandwidth implies that local coefficients are estimated using broad neighborhood information, producing a comparatively smooth spatial surface.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="gwr_pct_black_comparison.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="gwr_pct_black_comparison.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-cap="Geographically weighted regression (GWR) local coefficients for percent Black predicting violent felony crime rate. Red indicates stronger positive local association; blue indicates weaker or negative association. Shown for 2010–2012 vs 2013–2019." alt="Side-by-side maps of GWR local percent Black coefficients, before vs after."></a></p>
</figure>
</div>
<p>Consistent with this, the local %Black coefficient is uniformly positive and tightly distributed across precincts (min = 0.2328, median = 0.3176, max = 0.4034; mean = 0.3183). The quasi-global <span class="math inline">\(𝑅^2\)</span> is 0.3585, indicating that allowing coefficients to vary spatially yields a moderate improvement in explanatory power relative to a purely global specification.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="gwr_localR2_comparison.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="gwr_localR2_comparison.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-cap="GWR local R² surfaces for 2010–2012 vs 2013–2019. Higher values indicate that the local demographic model explains more variance in precinct crime rates in that area." alt="Side-by-side maps of GWR local R-squared, before vs after."></a></p>
</figure>
</div>
<p>In the post-Patternizr period (2013–2019), the optimal bandwidth shrinks dramatically to <span class="math inline">\(q≈0.022\)</span>, corresponding to approximately 1 of 76 precincts contributing to each local estimate. This indicates an extremely localized specification and a strong departure from spatial stationarity. The distribution of local %Black coefficients expands sharply and changes qualitatively: coefficients range from negative to extremely large positive values (min = −3.7466, median = 1.2650, max = 18.1796; mean = 2.4041). The quasi-global <span class="math inline">\(𝑅^2\)</span> rises to 0.9391, suggesting that the model—when permitted to vary at highly local scales—captures a very large share of precinct-level variation in crime rates.</p>
<p>However, the post-period GWR fit must be interpreted cautiously. The effective number of parameters increases markedly (approximately 39.2 in the post-period versus 6.7 in the pre-period), reflecting substantially greater model flexibility. As a result, the dramatic increase in quasi-global <span class="math inline">\(𝑅^2\)</span> is consistent with heightened spatial heterogeneity but may also reflect overfitting induced by the extremely small adaptive bandwidth.</p>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>Synthesizing the global, local, and GWR results yields a coherent descriptive pattern. First, violent crime becomes more spatially clustered after Patternizr (Moran’s I: 0.269 → 0.341), and this clustering is stronger than would be expected under a population-proportional null model in both periods (Monte Carlo <span class="math inline">\(p=0.003\)</span> pre; <span class="math inline">\(p=0.001\)</span> post). Second, racial composition remains highly clustered and changes little between periods (<span class="math inline">\(I=0.570\)</span> pre; <span class="math inline">\(𝐼=0.558 post\)</span>), indicating that segregation-like spatial structure persists regardless of policing regime. Third, despite these persistent forms of clustering, the spatial coincidence of Black-population hot spots and violent-crime hot spots disappears (overlap: 3 → 0 precincts).</p>
<p>The GWR results provide a plausible statistical complement to this spatial decoupling: before Patternizr, the association between %Black and crime rate is consistently positive and spatially smooth, whereas after Patternizr the relationship becomes sharply non-stationary, varying widely in magnitude and even sign across precincts. In practical terms, this implies that the post-Patternizr period is less well described by a single citywide race–crime gradient and more consistent with localized, place-specific dynamics. Importantly, this change is observational and does not, by itself, identify a causal effect of Patternizr. The post-period encompasses substantial social and demographic change, and the extreme localization implied by the selected bandwidth suggests that any causal interpretation would require additional identification strategies and sensitivity analyses.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>